//! What a catalog relation needs from the actual catalog.
//!
//! [`CatalogSource`] is deliberately narrow — the questions `pg_class`,
//! `pg_namespace`, `pg_attribute`, `pg_attrdef`, `pg_index` and
//! `pg_constraint` actually ask (list tables, list a table's columns, list a
//! table's column defaults, list a table's indexes, list a table's
//! constraints), not a general query interface. A real
//! `basin-catalog`-backed implementation is a follow-up; [`crate::mock`]
//! implements this trait in memory for tests, and for the `pg_type` relation
//! (which needs no catalog at all — see [`crate::pg_type`]).

use crate::Oid;

/// One row of `pg_namespace`, minus the columns nothing here reports yet
/// (`nspacl`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NamespaceInfo {
    pub oid: Oid,
    pub name: String,
    pub owner: Oid,
}

/// `pg_class.relkind` — what kind of relation a `pg_class` row describes.
///
/// Postgres has more variants (`t` toast, `f` foreign table, `p` partitioned
/// table, `I` partitioned index); only the ones a first increment's tests
/// exercise are here. Extending this is additive.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RelKind {
    OrdinaryTable,
    Index,
    View,
    Sequence,
    MaterializedView,
}

impl RelKind {
    /// The single-character code Postgres stores in `pg_class.relkind`.
    pub fn as_char(self) -> char {
        match self {
            RelKind::OrdinaryTable => 'r',
            RelKind::Index => 'i',
            RelKind::View => 'v',
            RelKind::Sequence => 'S',
            RelKind::MaterializedView => 'm',
        }
    }
}

/// One row of `pg_class`, minus the many columns nothing here reports yet
/// (`reltype`, `relam`, storage stats, ACLs, ...).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TableInfo {
    pub oid: Oid,
    pub name: String,
    pub namespace: Oid,
    pub owner: Oid,
    pub kind: RelKind,
}

/// One row of `pg_attribute`, restricted to the columns
/// `docs/migration/df-removal/11-pg-catalog-fidelity.md` calls out as
/// mattering in practice (`pg_attribute`'s own module docs have the full
/// live-verified column list and query).
///
/// `atttypmod`, `attidentity` and `attgenerated` used to be a tracked gap
/// (doc 11 §5) — this struct is what closed it. `attidentity`/`attgenerated`
/// are `Option<char>` rather than a `'\0'` sentinel because that is what real
/// Postgres's own "unset" value round-trips to: `SELECT
/// ''::"char" = attidentity FROM pg_attribute ...` and `attidentity::text`
/// (`length` 0) both confirm the unset value is the *empty* string, not a
/// one-byte NUL, when compared or cast the way ORM introspection queries do.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnInfo {
    pub table_oid: Oid,
    pub name: String,
    pub attnum: i16,
    pub type_oid: Oid,
    pub not_null: bool,
    /// The type modifier — `-1` (see [`basin_pgtype::typmod::UNSPECIFIED`])
    /// when the column's type carries none.
    pub atttypmod: i32,
    /// Whether this attribute slot is a dropped column. Real Postgres keeps a
    /// dropped column's `pg_attribute` row (mangled name, `atttypid` zeroed)
    /// rather than deleting it, so `attnum`s of later columns stay stable;
    /// this crate does not attempt that mangling, only the boolean flag.
    pub attisdropped: bool,
    /// `None` for an ordinary column, `Some('a')` for `GENERATED ALWAYS AS
    /// IDENTITY`, `Some('d')` for `GENERATED BY DEFAULT AS IDENTITY`.
    pub attidentity: Option<char>,
    /// `None` for an ordinary column, `Some('s')` for `GENERATED ALWAYS AS
    /// (...) STORED`.
    pub attgenerated: Option<char>,
}

/// One row of `pg_attrdef` — a single column's default expression.
///
/// `expr_src` is the default's **source text** (e.g. `"'anon'::character
/// varying"`, what `pg_get_expr(adbin, adrelid)` would print), not a
/// byte-compatible `nodeToString` parse tree the way real Postgres's `adbin`
/// column stores it internally. See [`crate::pg_attrdef`]'s module docs for
/// why: fabricating a parse tree we cannot actually re-parse would be a worse
/// gap than reporting the text plainly.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnDefaultInfo {
    pub oid: Oid,
    pub table_oid: Oid,
    /// The `attnum` (1-based) of the column this default belongs to.
    pub attnum: i16,
    pub expr_src: String,
}

/// One row of `pg_index`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IndexInfo {
    pub oid: Oid,
    pub table_oid: Oid,
    pub name: String,
    pub is_unique: bool,
    pub is_primary: bool,
    /// `attnum`s of the indexed columns, in index key order.
    pub column_attnums: Vec<i16>,
}

/// `pg_constraint.contype`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConstraintKind {
    Check,
    PrimaryKey,
    ForeignKey,
    Unique,
}

impl ConstraintKind {
    /// The single-character code Postgres stores in `pg_constraint.contype`.
    pub fn as_char(self) -> char {
        match self {
            ConstraintKind::Check => 'c',
            ConstraintKind::PrimaryKey => 'p',
            ConstraintKind::ForeignKey => 'f',
            ConstraintKind::Unique => 'u',
        }
    }
}

/// One row of `pg_constraint`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConstraintInfo {
    pub oid: Oid,
    pub table_oid: Oid,
    pub name: String,
    pub kind: ConstraintKind,
}

/// One `COMMENT ON TABLE` / `COMMENT ON COLUMN` attached to a table or one of
/// its columns — [`crate::pg_description`]'s only source.
///
/// Real `pg_description` covers every commentable object kind (schema, type,
/// function, operator, ...) via its `classoid` column; this narrows to the
/// two kinds `\d` and `pg_dump` actually read off a table (the table itself
/// and its columns), the same restriction [`crate::pg_attrdef`] makes for
/// column defaults. See [`crate::pg_description`]'s module docs for why both
/// still resolve to `classoid = pg_class`'s own oid: a column comment is
/// filed against the *table's* `pg_class` row with `objsubid` set to the
/// column's `attnum`, not against a `pg_attribute` row of its own — confirmed
/// live (see that module's docs).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommentInfo {
    /// `0` for a comment on the table itself; the column's `attnum` for a
    /// comment on one of its columns. Matches `pg_description.objsubid`
    /// exactly.
    pub objsubid: i32,
    pub description: String,
}

/// One `CREATE TYPE ... AS ENUM` declaration — [`crate::pg_enum`]'s source.
///
/// Mirrors `basin_catalog::enums::EnumTypeDef` (project, name, ordered
/// `labels`) plus the `oid`/`namespace` a real `pg_type`/`pg_enum` row
/// needs and `EnumTypeDef` itself does not carry (Basin addresses an enum
/// type by `(ProjectId, name)`, not by an integer id — see
/// `crates/basin-catalog/src/enums.rs`'s own module docs). `CatalogSource`
/// is a plain-data boundary (see [`crate::real_source`]'s module docs), so
/// this crate does not depend on `basin-catalog` to name that type; a
/// caller that has one converts it to this shape the same way
/// [`crate::real_source::RealCatalogSource`] converts already-`.await`-ed
/// `basin-catalog` data elsewhere.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EnumTypeInfo {
    pub oid: Oid,
    pub namespace: Oid,
    pub name: String,
    /// Ordered labels; the first is Postgres's `enumsortorder = 1`, not
    /// `0` — confirmed live (see [`crate::pg_enum`]'s module docs).
    pub labels: Vec<String>,
}

/// One `CREATE SEQUENCE` (or `SERIAL`-column-owned sequence)'s parameters —
/// [`crate::pg_sequence`]'s source.
///
/// Mirrors `basin_catalog::sequences::SequenceDef` (`start`, `increment`,
/// `min_value`, `max_value`, `cache_size`, `cycle` — the exact fields
/// [`crate::pg_sequence`] needs) plus `oid`, which is the sequence's own
/// `pg_class.oid` (`pg_sequence.seqrelid` in real Postgres — the same row
/// [`RelKind::Sequence`] already marks in [`TableInfo`]).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SequenceInfo {
    /// The sequence's own relation oid — `pg_sequence.seqrelid`, matching a
    /// [`TableInfo`] row of [`RelKind::Sequence`].
    pub oid: Oid,
    /// `pg_sequence.seqtypid` — the data type values are generated as.
    /// Real Postgres defaults a plain `CREATE SEQUENCE` to `int8` and a
    /// `SERIAL`/`BIGSERIAL` column's owned sequence to the owning column's
    /// type (confirmed live: a plain sequence reports `bigint`, a `serial`
    /// column's owned sequence reports `integer`). `basin_catalog::
    /// sequences::SequenceDef` does not track column ownership, so this
    /// crate cannot yet distinguish the two cases; callers should default
    /// to `basin_pgtype::oid::INT8`, matching the plain-`CREATE SEQUENCE`
    /// case.
    pub type_oid: Oid,
    pub start: i64,
    pub increment: i64,
    pub max_value: i64,
    pub min_value: i64,
    pub cache_size: i64,
    pub cycle: bool,
}

/// What a [`crate::SystemView`] needs from the underlying catalog.
///
/// Every method returns owned data rather than borrowing, since the source
/// may be a live query against `basin-catalog` with no stable borrow to
/// return.
pub trait CatalogSource {
    /// All schemas in the current project's `search_path` scope.
    fn namespaces(&self) -> Vec<NamespaceInfo>;
    /// All relations (tables, indexes, views, ...) in the current project.
    fn tables(&self) -> Vec<TableInfo>;
    /// The columns of one table, in `attnum` order.
    fn columns(&self, table_oid: Oid) -> Vec<ColumnInfo>;
    /// The column default expressions defined on one table (`pg_attrdef`).
    /// Not every column has one — only those with a `DEFAULT` clause.
    fn column_defaults(&self, table_oid: Oid) -> Vec<ColumnDefaultInfo>;
    /// The indexes defined on one table.
    fn indexes(&self, table_oid: Oid) -> Vec<IndexInfo>;
    /// The constraints defined on one table.
    fn constraints(&self, table_oid: Oid) -> Vec<ConstraintInfo>;
    /// The comments (`pg_description`) attached to one table and its
    /// columns. Not every table (or column) has one.
    fn comments(&self, table_oid: Oid) -> Vec<CommentInfo>;
    /// Every `CREATE TYPE ... AS ENUM` declared in the current project
    /// (`pg_enum`, and eventually `pg_type`'s own enum rows).
    fn enum_types(&self) -> Vec<EnumTypeInfo>;
    /// Every sequence's parameters in the current project (`pg_sequence`).
    /// Not table-scoped, like [`Self::tables`] — a sequence is its own
    /// relation, not owned by the query in `CatalogSource`'s sense (real
    /// Postgres's sequence-owned-by-column link lives in `pg_depend`, which
    /// this trait does not model — see [`crate::pg_depend`]'s module docs).
    fn sequences(&self) -> Vec<SequenceInfo>;
}
