//! Project-level COW branch (fork) admin route.
//!
//! ## Surface
//!
//! | Verb + Path                                          | Action             | Status |
//! |------------------------------------------------------|--------------------|--------|
//! | `POST /admin/v1/projects/:project_id/fork`           | COW branch project | 200    |
//!
//! ## Auth
//!
//! Same admin gate as all `/admin/v1/*` routes — every request requires a JWT
//! with `is_admin: true`. The `project_id` claim in the token must match the
//! `:project_id` path segment (the source project).
//!
//! ## Wire shape
//!
//! `POST /admin/v1/projects/:project_id/fork` body:
//! ```json
//! { "dst_project_id": "<string>" }
//! ```
//!
//! The cloud generates the destination project id and passes it; the engine
//! does not mint it.
//!
//! Success response:
//! ```json
//! { "ok": true, "forked_tables": 2 }
//! ```
//!
//! `forked_tables` is the number of tables copied from the source project.
//! When the source project has no tables the value is 0 and the response is
//! still `ok: true`.
//!
//! ## COW semantics
//!
//! Each table in the source project is forked into the destination project
//! via [`Catalog::fork_table_to_project`]. Data files (Parquet objects on
//! object storage) are **shared by reference** — no bytes are copied. The
//! destination's catalog metadata points at the same file paths. Subsequent
//! writes to either side produce new files; reads from either side see only
//! the files in their own snapshot lineage.

use std::sync::Arc;

use axum::extract::{Path, State};
use axum::http::HeaderMap;
use axum::response::{IntoResponse, Response};
use axum::Json;
use basin_catalog::Catalog as _;
use basin_common::ProjectId;
use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::errors::ApiError;
use crate::server::{authorize, Inner};

// ---------------------------------------------------------------------------
// Admin gate helpers (mirrors admin_backups.rs)
// ---------------------------------------------------------------------------

fn require_admin(claims: &basin_auth::Claims) -> Result<(), ApiError> {
    if !claims.is_admin {
        return Err(ApiError::unauthenticated(
            "admin endpoint requires `is_admin: true` claim",
        ));
    }
    Ok(())
}

fn assert_admin_for_path_project(
    claims: &basin_auth::Claims,
    path_project_id: &ProjectId,
) -> Result<(), ApiError> {
    // The control-plane super-admin token — scoped to INTERNAL_AUTH_PROJECT_ID —
    // may operate on any project. That is the single deploy-time `is_admin`
    // token the cloud control plane mints to provision and administer every
    // project (see `basin_auth::Claims::is_admin` docs); without this it could
    // create projects (the unscoped `POST /admin/v1/projects` route) but not
    // fork them, which is path-scoped.
    if claims.project_id.to_string() == basin_auth::INTERNAL_AUTH_PROJECT_ID {
        return Ok(());
    }
    if claims.project_id != *path_project_id {
        return Err(ApiError::forbidden(format!(
            "admin token scoped to project {} cannot operate on project {}",
            claims.project_id, path_project_id,
        )));
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// POST /admin/v1/projects/:project_id/fork
// ---------------------------------------------------------------------------

/// `POST /admin/v1/projects/:project_id/fork` request body.
#[derive(Debug, Deserialize)]
pub(crate) struct ForkProjectRequest {
    /// The destination project id — generated by the cloud, passed verbatim.
    pub dst_project_id: String,
}

/// `POST /admin/v1/projects/:project_id/fork` response.
#[derive(Debug, Serialize)]
pub(crate) struct ForkProjectResponse {
    pub ok: bool,
    pub forked_tables: usize,
}

/// Fork all tables in `:project_id` (source) into `dst_project_id` (destination).
///
/// For every table in the source project, calls
/// [`Catalog::fork_table_to_project`] to create an entry in the destination
/// project whose catalog metadata references the same data files. This is the
/// engine-side half of the cloud's branch/fork primitive.
///
/// The destination project must not already contain any of the source tables;
/// if it does the handler returns a 409-style catalog error so the cloud can
/// surface a clear conflict to the operator.
#[axum::debug_handler]
pub(crate) async fn fork_project(
    State(state): State<Arc<Inner>>,
    headers: HeaderMap,
    Path(project_id): Path<String>,
    Json(req): Json<ForkProjectRequest>,
) -> Result<Response, ApiError> {
    let claims = authorize(&state, &headers).await?;
    require_admin(&claims)?;

    let src_project: ProjectId = project_id
        .parse()
        .map_err(|e| ApiError::invalid(format!("invalid project_id: {e}")))?;
    assert_admin_for_path_project(&claims, &src_project)?;

    let dst_project: ProjectId = req
        .dst_project_id
        .parse()
        .map_err(|e| ApiError::invalid(format!("invalid dst_project_id: {e}")))?;

    if dst_project == src_project {
        return Err(ApiError::invalid(
            "dst_project_id must differ from the source project_id",
        ));
    }

    let catalog = state.cfg.engine.config().catalog.clone();

    // Enumerate the source project's tables.
    let tables = catalog
        .list_tables(&src_project)
        .await
        .map_err(ApiError::from)?;

    // Fork each table into the destination project under the same name.
    let mut forked: usize = 0;
    for table in &tables {
        catalog
            .fork_table_to_project(&src_project, table, &dst_project, table)
            .await
            .map_err(|e| {
                // Surface a clear conflict error for the `dst table already
                // exists` case so the cloud can act on it rather than seeing
                // a generic 500.  Internal identifiers (project / table names,
                // storage errors) are logged server-side only and never sent
                // to the caller.
                let msg = e.to_string();
                if msg.contains("already exists") {
                    tracing::warn!(
                        src_project = %src_project,
                        dst_project = %dst_project,
                        table = %table,
                        error = %msg,
                        "fork conflict: destination already contains a table",
                    );
                    ApiError::new(
                        crate::errors::ErrorCode::InvalidRequest,
                        "fork conflict: destination already contains a table",
                    )
                } else {
                    ApiError::from(e)
                }
            })?;
        forked += 1;
    }

    tracing::info!(
        src_project = %src_project,
        dst_project = %dst_project,
        forked_tables = forked,
        "project COW fork complete",
    );

    Ok(Json(ForkProjectResponse {
        ok: true,
        forked_tables: forked,
    })
    .into_response())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use arrow_schema::{DataType, Field, Schema};
    use basin_catalog::{Catalog as _, DataFileRef, InMemoryCatalog, SnapshotId};
    use basin_common::{ProjectId, TableName};

    // -------------------------------------------------------------------------
    // Helper: create a table and append one data file so it has a real snapshot.
    // -------------------------------------------------------------------------

    async fn seed_table(
        cat: &Arc<InMemoryCatalog>,
        project: &ProjectId,
        name: &str,
    ) -> TableName {
        let table = TableName::new(name).unwrap();
        let schema = Schema::new(vec![Field::new("v", DataType::Int64, false)]);
        cat.create_table(project, &table, &schema)
            .await
            .expect("create_table");

        let f = DataFileRef {
            path: format!("{name}_data.parquet"),
            row_count: 5,
            size_bytes: 512,
            column_stats: Default::default(),
            bloom_filters: Default::default(),
            hll_sketches: Default::default(),
            tdigest_sketches: Default::default(),
        };
        cat.append_data_files(project, &table, SnapshotId::GENESIS, vec![f])
            .await
            .expect("append");

        table
    }

    // -------------------------------------------------------------------------
    // Core fork test: two tables in src_project are forked to dst_project.
    // -------------------------------------------------------------------------

    #[tokio::test]
    async fn fork_project_copies_tables_with_shared_files() {
        let cat = Arc::new(InMemoryCatalog::new());
        let src = ProjectId::new();
        let dst = ProjectId::new();

        // Create two tables in the source project.
        let t_a = seed_table(&cat, &src, "alpha").await;
        let t_b = seed_table(&cat, &src, "beta").await;

        // List before fork.
        let src_tables = cat.list_tables(&src).await.expect("list src");
        assert_eq!(src_tables.len(), 2);

        // Fork each table to dst (mirroring what the route handler does).
        for table in &src_tables {
            cat.fork_table_to_project(&src, table, &dst, table)
                .await
                .expect("fork_table_to_project");
        }

        // dst now has the same tables.
        let dst_tables = cat.list_tables(&dst).await.expect("list dst");
        assert_eq!(dst_tables.len(), 2);
        assert!(dst_tables.contains(&t_a));
        assert!(dst_tables.contains(&t_b));

        // Each dst table has the same snapshot / file content as the src.
        for table in &[&t_a, &t_b] {
            let src_meta = cat.load_table(&src, table).await.expect("load src");
            let dst_meta = cat.load_table(&dst, table).await.expect("load dst");

            assert_eq!(
                src_meta.current_snapshot, dst_meta.current_snapshot,
                "fork should start at the same snapshot head"
            );

            // Verify the file paths are the same (shared, not deep-copied).
            let src_files: Vec<_> = src_meta
                .snapshots
                .iter()
                .flat_map(|s| s.data_files.iter().map(|f| f.path.clone()))
                .collect();
            let dst_files: Vec<_> = dst_meta
                .snapshots
                .iter()
                .flat_map(|s| s.data_files.iter().map(|f| f.path.clone()))
                .collect();
            assert_eq!(
                src_files, dst_files,
                "forked table must reference the same file paths (COW, not deep-copy)"
            );
        }

        // Writes to src must not affect dst lineage.
        let extra = DataFileRef {
            path: "alpha_v2.parquet".to_string(),
            row_count: 1,
            size_bytes: 100,
            column_stats: Default::default(),
            bloom_filters: Default::default(),
            hll_sketches: Default::default(),
            tdigest_sketches: Default::default(),
        };
        let src_meta = cat.load_table(&src, &t_a).await.unwrap();
        cat.append_data_files(&src, &t_a, src_meta.current_snapshot, vec![extra])
            .await
            .expect("post-fork write to src");

        let src_after = cat.load_table(&src, &t_a).await.unwrap();
        let dst_after = cat.load_table(&dst, &t_a).await.unwrap();
        assert_ne!(
            src_after.current_snapshot, dst_after.current_snapshot,
            "post-fork write to src must not advance dst snapshot"
        );
    }

    // -------------------------------------------------------------------------
    // Empty source project: fork returns forked_tables = 0 and is still ok.
    // -------------------------------------------------------------------------

    #[tokio::test]
    async fn fork_empty_project_returns_zero_tables() {
        let cat = Arc::new(InMemoryCatalog::new());
        let src = ProjectId::new();
        let dst = ProjectId::new();

        // No tables in src — just list and iterate (nothing to fork).
        let tables = cat.list_tables(&src).await.expect("list");
        assert!(tables.is_empty());

        let mut forked: usize = 0;
        for table in &tables {
            cat.fork_table_to_project(&src, table, &dst, table)
                .await
                .expect("fork");
            forked += 1;
        }
        assert_eq!(forked, 0);
    }

    // -------------------------------------------------------------------------
    // Conflict: forking the same table twice returns an error.
    // -------------------------------------------------------------------------

    #[tokio::test]
    async fn fork_duplicate_table_returns_conflict() {
        let cat = Arc::new(InMemoryCatalog::new());
        let src = ProjectId::new();
        let dst = ProjectId::new();

        let t = seed_table(&cat, &src, "orders").await;

        // First fork succeeds.
        cat.fork_table_to_project(&src, &t, &dst, &t)
            .await
            .expect("first fork");

        // Second fork of the same table must fail.
        let err = cat
            .fork_table_to_project(&src, &t, &dst, &t)
            .await
            .unwrap_err();
        assert!(
            err.to_string().contains("already exists"),
            "expected 'already exists' error, got: {err}"
        );
    }
}
