#!/usr/bin/env python3
"""Bundle dashboard/data/*.json into dashboard/data/results.js.

Browsers block fetch() of local files when the page is opened via file://.
This script wraps the same JSON in a script-tag-loadable JS file
(`window.__BASIN_RESULTS = {...}`) so the dashboard works on a plain
double-click of index.html, no server required.

Run after `cargo test -p basin-integration-tests --tests`.
"""

from __future__ import annotations
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA_DIR = HERE / "data"


def main() -> int:
    if not DATA_DIR.is_dir():
        print(f"no data dir: {DATA_DIR}", file=sys.stderr)
        return 1

    manifest_path = DATA_DIR / "manifest.json"
    if not manifest_path.exists():
        print(f"missing manifest: {manifest_path}", file=sys.stderr)
        return 1
    manifest = json.loads(manifest_path.read_text())

    reports: dict[str, dict] = {}
    for p in sorted(DATA_DIR.glob("*.json")):
        if p.name == "manifest.json":
            continue
        try:
            reports[p.stem] = json.loads(p.read_text())
        except json.JSONDecodeError as e:
            print(f"skipping malformed {p.name}: {e}", file=sys.stderr)

    bundle = {"manifest": manifest, "reports": reports}
    out = DATA_DIR / "results.js"
    out.write_text(
        "// auto-generated by dashboard/bundle.py — do not edit by hand\n"
        f"window.__BASIN_RESULTS = {json.dumps(bundle, indent=2)};\n"
    )
    print(f"wrote {out} ({len(reports)} reports, {out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
