// Code generated by basin gen types — DO NOT EDIT.

package database;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.Nullable;

public final class Orders {
    @JsonProperty("id")
    public final java.util.UUID id;
    @JsonProperty("user_id")
    public final @Nullable java.util.UUID user_id;
    @JsonProperty("total")
    public final java.math.BigDecimal total;
    @JsonProperty("metadata")
    public final @Nullable com.fasterxml.jackson.databind.JsonNode metadata;

    public Orders(@JsonProperty("id") java.util.UUID id, @JsonProperty("user_id") @Nullable java.util.UUID user_id, @JsonProperty("total") java.math.BigDecimal total, @JsonProperty("metadata") @Nullable com.fasterxml.jackson.databind.JsonNode metadata)
    {
        this.id = id;
        this.user_id = user_id;
        this.total = total;
        this.metadata = metadata;
    }
}

public final class Users {
    @JsonProperty("id")
    public final java.util.UUID id;
    @JsonProperty("email")
    public final String email;
    @JsonProperty("created_at")
    public final @Nullable java.time.OffsetDateTime created_at;
    @JsonProperty("embedding")
    public final @Nullable float[] embedding;
    @JsonProperty("score")
    public final int score;

    public Users(@JsonProperty("id") java.util.UUID id, @JsonProperty("email") String email, @JsonProperty("created_at") @Nullable java.time.OffsetDateTime created_at, @JsonProperty("embedding") @Nullable float[] embedding, @JsonProperty("score") int score)
    {
        this.id = id;
        this.email = email;
        this.created_at = created_at;
        this.embedding = embedding;
        this.score = score;
    }
}

