# Code generated by basin gen types — DO NOT EDIT.

from datetime import datetime
from decimal import Decimal
from pydantic import BaseModel
from typing import Any, Optional
from typing import Optional
from uuid import UUID

class Orders(BaseModel):
    id: UUID
    user_id: Optional[UUID]
    total: Decimal
    metadata: Optional[Any]

class Users(BaseModel):
    id: UUID
    email: str
    created_at: Optional[datetime]
    embedding: Optional[list[float]]
    score: int

