// Code generated by basin gen types — DO NOT EDIT.

import Foundation

public struct Orders: Codable, Sendable {
    public let id: UUID
    public let userId: UUID?
    public let total: String
    public let metadata: AnyCodable?

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case total
        case metadata
    }
}

public struct Users: Codable, Sendable {
    public let id: UUID
    public let email: String
    public let createdAt: Date?
    public let embedding: [Float]?
    public let score: Int32

    enum CodingKeys: String, CodingKey {
        case id
        case email
        case createdAt = "created_at"
        case embedding
        case score
    }
}

