// Code generated by basin gen types — DO NOT EDIT.
// ignore_for_file: always_specify_types

class Orders {
  final String id;
  final String? user_id;
  final String total;
  final Map<String, dynamic>? metadata;

  const Orders({
    required this.id,
    this.user_id,
    required this.total,
    this.metadata,
  });

  factory Orders.fromJson(Map<String, dynamic> j) =>
    Orders(
      id: j['id'] as String,
      user_id: j['user_id'] as String?,
      total: j['total'] as String,
      metadata: j['metadata'] as Map<String, dynamic>?,
    );

  Map<String, dynamic> toJson() => {
    'id': id,
    'user_id': user_id,
    'total': total,
    'metadata': metadata,
  };
}

class Users {
  final String id;
  final String email;
  final DateTime? created_at;
  final List<double>? embedding;
  final int score;

  const Users({
    required this.id,
    required this.email,
    this.created_at,
    this.embedding,
    required this.score,
  });

  factory Users.fromJson(Map<String, dynamic> j) =>
    Users(
      id: j['id'] as String,
      email: j['email'] as String,
      created_at: j['created_at'] == null ? null : DateTime.parse(j['created_at'] as String),
      embedding: j['embedding'] as List<double>?,
      score: j['score'] as int,
    );

  Map<String, dynamic> toJson() => {
    'id': id,
    'email': email,
    'created_at': created_at,
    'embedding': embedding,
    'score': score,
  };
}

