// Code generated by basin gen types — DO NOT EDIT.

use serde::{Deserialize, Serialize};

use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Orders {
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    pub total: String,
    pub metadata: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Users {
    pub id: uuid::Uuid,
    pub email: String,
    pub created_at: Option<String>,
    pub embedding: Option<Vec<f32>>,
    pub score: i32,
}

