<?php
// Code generated by basin gen types — DO NOT EDIT.

declare(strict_types=1);

namespace database;

final class Orders
{
    public function __construct(
        public readonly string $id,
        public readonly ?string $user_id,
        public readonly string $total,
        public readonly mixed $metadata,
    ) {}

    /** @param array<string,mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: (string) $data['id'],
            user_id: isset($data['user_id']) ? (string) $data['user_id'] : null,
            total: (string) $data['total'],
            metadata: isset($data['metadata']) ? (mixed) $data['metadata'] : null,
        );
    }
}

final class Users
{
    public function __construct(
        public readonly string $id,
        public readonly string $email,
        public readonly ?string $created_at,
        public readonly ?array $embedding,
        public readonly int $score,
    ) {}

    /** @param array<string,mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            id: (string) $data['id'],
            email: (string) $data['email'],
            created_at: isset($data['created_at']) ? (string) $data['created_at'] : null,
            embedding: isset($data['embedding']) ? (array) $data['embedding'] : null,
            score: (int) $data['score'],
        );
    }
}

