# Code generated by basin gen types — DO NOT EDIT.
# frozen_string_literal: true

Orders = Struct.new(:id, :user_id, :total, :metadata, keyword_init: true) do
  ATTRIBUTES = [:id, :user_id, :total, :metadata].freeze
  # @return [String] id
  # @return [String] user_id
  # @return [BigDecimal] total
  # @return [Hash] metadata
end

Users = Struct.new(:id, :email, :created_at, :embedding, :score, keyword_init: true) do
  ATTRIBUTES = [:id, :email, :created_at, :embedding, :score].freeze
  # @return [String] id
  # @return [String] email
  # @return [Time] created_at
  # @return [Array] embedding
  # @return [Integer] score
end

