// Code generated by basin gen types — DO NOT EDIT.

export interface Table_Orders {
  id: string;
  user_id: string | null;
  total: string;
  metadata: Record<string, unknown> | null;
}

export interface Table_Users {
  id: string;
  email: string;
  created_at: string | null;
  embedding: number[] | null;
  score: number;
}

export interface Database {
  Tables: {
    orders: Table_Orders;
    users: Table_Users;
  };
}
