// Code generated by basin gen types — DO NOT EDIT.

using System.Text.Json.Serialization;
using System.Text.Json;

namespace database;

public sealed record Orders(
    [JsonPropertyName("id")] Guid Id,
    [JsonPropertyName("user_id")] Guid? UserId,
    [JsonPropertyName("total")] decimal Total,
    [JsonPropertyName("metadata")] JsonElement? Metadata
);

public sealed record Users(
    [JsonPropertyName("id")] Guid Id,
    [JsonPropertyName("email")] string Email,
    [JsonPropertyName("created_at")] DateTimeOffset? CreatedAt,
    [JsonPropertyName("embedding")] float[]? Embedding,
    [JsonPropertyName("score")] int Score
);

