// Code generated by basin gen types — DO NOT EDIT.

package database

import (
	"encoding/json"
	"time"
)

type Orders struct {
	Id [16]byte `json:"id" db:"id"`
	UserId *[16]byte `json:"user_id" db:"user_id"`
	Total string `json:"total" db:"total"`
	Metadata json.RawMessage `json:"metadata" db:"metadata"`
}

type Users struct {
	Id [16]byte `json:"id" db:"id"`
	Email string `json:"email" db:"email"`
	CreatedAt *time.Time `json:"created_at" db:"created_at"`
	Embedding []float32 `json:"embedding" db:"embedding"`
	Score int32 `json:"score" db:"score"`
}

