//! IDENTITY columns + SERIAL/BIGSERIAL/SMALLSERIAL syntactic sugar.
//!
//! Bar: every shape below runs end-to-end against the engine — CREATE
//! TABLE mints a backing sequence, INSERT auto-fills omitted IDENTITY
//! columns from nextval, GENERATED ALWAYS rejects user-supplied values
//! unless OVERRIDING SYSTEM VALUE is set, OVERRIDING USER VALUE on a BY
//! DEFAULT column discards the user's literal and re-fills from nextval.
//!
//! Forms exercised:
//!
//! ```sql
//! CREATE TABLE a (id BIGINT GENERATED ALWAYS AS IDENTITY, name TEXT);
//! INSERT INTO a (name) VALUES ('x'), ('y');        -- id=1, id=2
//! INSERT INTO a (id, name) VALUES (99, 'z');       -- REJECTED
//! INSERT INTO a (id, name) OVERRIDING SYSTEM VALUE VALUES (99, 'z');  -- OK
//!
//! CREATE TABLE b (id INT GENERATED BY DEFAULT AS IDENTITY, name TEXT);
//! INSERT INTO b (id, name) VALUES (10, 'p');       -- accepts literal
//! INSERT INTO b (name) VALUES ('q');               -- auto-fills nextval
//! INSERT INTO b (id, name) OVERRIDING USER VALUE VALUES (99, 'r');  -- discards 99
//!
//! CREATE TABLE c (id SERIAL, name TEXT);
//! INSERT INTO c (id, name) VALUES (5, 's');        -- accepts literal (BY DEFAULT)
//! INSERT INTO c (name) VALUES ('t');               -- auto-fills nextval
//!
//! CREATE TABLE d (id BIGSERIAL, name TEXT);  -- BIGSERIAL variant
//! CREATE TABLE e (id SMALLSERIAL, name TEXT); -- SMALLSERIAL variant
//!
//! UPDATE a SET id = 5 WHERE name = 'x';            -- REJECTED (ALWAYS)
//! ```

#![allow(clippy::print_stdout)]

use std::sync::Arc;

use arrow_array::Int64Array;
use basin_catalog::InMemoryCatalog;
use basin_common::TenantId;
use basin_engine::{Engine, EngineConfig, ExecResult};
use object_store::local::LocalFileSystem;
use tempfile::TempDir;

fn rows_int64(batches: &[arrow_array::RecordBatch], name: &str) -> Vec<i64> {
    let mut out = Vec::new();
    for b in batches {
        let arr = b
            .column_by_name(name)
            .unwrap_or_else(|| panic!("missing column {name}"))
            .as_any()
            .downcast_ref::<Int64Array>()
            .unwrap_or_else(|| panic!("column {name} is not Int64"));
        for i in 0..arr.len() {
            if arr.is_null(i) {
                continue;
            }
            out.push(arr.value(i));
        }
    }
    out
}

async fn engine_in(dir: &TempDir) -> Engine {
    let fs = LocalFileSystem::new_with_prefix(dir.path()).unwrap();
    let storage = basin_storage::Storage::new(basin_storage::StorageConfig {
        object_store: Arc::new(fs),
        root_prefix: None,
        disk_cache: basin_integration_tests::cache_defaults::default_test_disk_cache(),
        page_cache: basin_integration_tests::cache_defaults::default_test_page_cache(),
    });
    let catalog: Arc<dyn basin_catalog::Catalog> = Arc::new(InMemoryCatalog::new());
    Engine::new(EngineConfig {
        storage,
        catalog,
        shard: None,
    })
}

/// `CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY, name TEXT)` —
/// omitted-column INSERT fills from nextval (1, 2). Literal INSERT is
/// rejected unless OVERRIDING SYSTEM VALUE.
#[tokio::test]
async fn identity_always_omitted_fills_from_nextval() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute("CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY, name TEXT NOT NULL)")
        .await
        .expect("CREATE TABLE with IDENTITY ALWAYS");

    sess.execute("INSERT INTO t (name) VALUES ('a'), ('b')")
        .await
        .expect("INSERT with id omitted");

    let res = sess
        .execute("SELECT id, name FROM t ORDER BY id")
        .await
        .unwrap();
    match res {
        ExecResult::Rows { batches, .. } => {
            assert_eq!(rows_int64(&batches, "id"), vec![1, 2]);
        }
        other => panic!("unexpected: {other:?}"),
    }
}

#[tokio::test]
async fn identity_always_rejects_user_value() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute("CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY, name TEXT NOT NULL)")
        .await
        .unwrap();

    let err = sess
        .execute("INSERT INTO t (id, name) VALUES (99, 'c')")
        .await
        .expect_err("ALWAYS IDENTITY should reject user value");
    let msg = format!("{err}");
    assert!(
        msg.contains("GENERATED ALWAYS") || msg.contains("OVERRIDING"),
        "unexpected error message: {msg}"
    );
}

#[tokio::test]
async fn identity_always_overriding_system_value_accepts_literal() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute("CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY, name TEXT NOT NULL)")
        .await
        .unwrap();

    sess.execute("INSERT INTO t (id, name) OVERRIDING SYSTEM VALUE VALUES (99, 'c')")
        .await
        .expect("OVERRIDING SYSTEM VALUE should accept literal");

    let res = sess
        .execute("SELECT id FROM t WHERE name = 'c'")
        .await
        .unwrap();
    match res {
        ExecResult::Rows { batches, .. } => {
            assert_eq!(rows_int64(&batches, "id"), vec![99]);
        }
        other => panic!("unexpected: {other:?}"),
    }
}

#[tokio::test]
async fn identity_by_default_accepts_user_value() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute(
        "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY, name TEXT NOT NULL)",
    )
    .await
    .expect("CREATE TABLE with IDENTITY BY DEFAULT");

    // Literal accepted.
    sess.execute("INSERT INTO t (id, name) VALUES (10, 'a')")
        .await
        .expect("BY DEFAULT IDENTITY accepts literal");
    // Omitted → nextval.
    sess.execute("INSERT INTO t (name) VALUES ('b')")
        .await
        .expect("BY DEFAULT IDENTITY auto-fills");

    let res = sess
        .execute("SELECT id, name FROM t ORDER BY name")
        .await
        .unwrap();
    match res {
        ExecResult::Rows { batches, .. } => {
            let ids = rows_int64(&batches, "id");
            assert_eq!(ids.len(), 2);
            assert_eq!(ids[0], 10);
            // The nextval-filled row gets the sequence's first value (1).
            assert_eq!(ids[1], 1);
        }
        other => panic!("unexpected: {other:?}"),
    }
}

#[tokio::test]
async fn identity_by_default_overriding_user_value_discards_literal() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute(
        "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY, name TEXT NOT NULL)",
    )
    .await
    .unwrap();

    sess.execute("INSERT INTO t (id, name) OVERRIDING USER VALUE VALUES (99, 'r')")
        .await
        .expect("OVERRIDING USER VALUE should discard literal");

    let res = sess
        .execute("SELECT id FROM t WHERE name = 'r'")
        .await
        .unwrap();
    match res {
        ExecResult::Rows { batches, .. } => {
            // 99 was discarded; sequence's first value (1) was used.
            assert_eq!(rows_int64(&batches, "id"), vec![1]);
        }
        other => panic!("unexpected: {other:?}"),
    }
}

#[tokio::test]
async fn serial_accepts_literal_and_auto_fills() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute("CREATE TABLE u (id SERIAL, name TEXT NOT NULL)")
        .await
        .expect("CREATE TABLE with SERIAL");

    // SERIAL = IDENTITY BY DEFAULT — literal accepted.
    sess.execute("INSERT INTO u (id, name) VALUES (99, 'a')")
        .await
        .expect("SERIAL accepts literal id");
    // Omitted → nextval.
    sess.execute("INSERT INTO u (name) VALUES ('b')")
        .await
        .expect("SERIAL auto-fills omitted id");

    let res = sess
        .execute("SELECT id, name FROM u ORDER BY name")
        .await
        .unwrap();
    match res {
        ExecResult::Rows { batches, .. } => {
            let ids = rows_int64(&batches, "id");
            assert_eq!(ids, vec![99, 1]);
        }
        other => panic!("unexpected: {other:?}"),
    }
}

#[tokio::test]
async fn bigserial_creates_table() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute("CREATE TABLE v (id BIGSERIAL, name TEXT NOT NULL)")
        .await
        .expect("CREATE TABLE with BIGSERIAL");
    sess.execute("INSERT INTO v (name) VALUES ('a'), ('b'), ('c')")
        .await
        .expect("INSERT auto-fills BIGSERIAL");
    let res = sess
        .execute("SELECT id FROM v ORDER BY id")
        .await
        .unwrap();
    match res {
        ExecResult::Rows { batches, .. } => {
            assert_eq!(rows_int64(&batches, "id"), vec![1, 2, 3]);
        }
        other => panic!("unexpected: {other:?}"),
    }
}

#[tokio::test]
async fn smallserial_creates_table() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute("CREATE TABLE w (id SMALLSERIAL, name TEXT NOT NULL)")
        .await
        .expect("CREATE TABLE with SMALLSERIAL");
    sess.execute("INSERT INTO w (name) VALUES ('a')")
        .await
        .expect("INSERT auto-fills SMALLSERIAL");
    let res = sess
        .execute("SELECT id FROM w")
        .await
        .unwrap();
    match res {
        ExecResult::Rows { batches, .. } => {
            assert_eq!(rows_int64(&batches, "id"), vec![1]);
        }
        other => panic!("unexpected: {other:?}"),
    }
}

#[tokio::test]
async fn update_rejects_identity_always_column() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute("CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY, name TEXT NOT NULL)")
        .await
        .unwrap();
    sess.execute("INSERT INTO t (name) VALUES ('a')")
        .await
        .unwrap();

    let err = sess
        .execute("UPDATE t SET id = 99 WHERE name = 'a'")
        .await
        .expect_err("UPDATE on IDENTITY ALWAYS should reject");
    let msg = format!("{err}");
    assert!(
        msg.contains("GENERATED ALWAYS") || msg.contains("can only be updated"),
        "unexpected error message: {msg}"
    );
}

/// Two IDENTITY-style sequences on different tables coexist without
/// stepping on each other's namespace — important because the implicit
/// `<table>_<col>_seq` name is per-table.
#[tokio::test]
async fn two_identity_tables_have_independent_sequences() {
    let dir = TempDir::new().unwrap();
    let engine = engine_in(&dir).await;
    let sess = engine.open_session(TenantId::new()).await.unwrap();

    sess.execute("CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY, name TEXT NOT NULL)")
        .await
        .unwrap();
    sess.execute("CREATE TABLE u (id BIGINT GENERATED ALWAYS AS IDENTITY, name TEXT NOT NULL)")
        .await
        .unwrap();
    sess.execute("INSERT INTO t (name) VALUES ('a'), ('b')")
        .await
        .unwrap();
    sess.execute("INSERT INTO u (name) VALUES ('p')")
        .await
        .unwrap();
    sess.execute("INSERT INTO t (name) VALUES ('c')")
        .await
        .unwrap();

    let res = sess
        .execute("SELECT id FROM t ORDER BY id")
        .await
        .unwrap();
    match res {
        ExecResult::Rows { batches, .. } => {
            assert_eq!(rows_int64(&batches, "id"), vec![1, 2, 3]);
        }
        other => panic!("unexpected: {other:?}"),
    }
    let res = sess.execute("SELECT id FROM u").await.unwrap();
    match res {
        ExecResult::Rows { batches, .. } => {
            assert_eq!(rows_int64(&batches, "id"), vec![1]);
        }
        other => panic!("unexpected: {other:?}"),
    }
}
