//! Regression tests for SQL shapes real ORMs emit that previously failed.
//!
//! Each test reproduces a specific live-ORM failure mode against the engine
//! directly (no pgwire), so it runs in CI without the ORM's own toolchain:
//!
//! - Drizzle `INSERT INTO t (id, …) VALUES (default, …)` on a SERIAL/identity
//!   column — the explicit `DEFAULT` keyword must draw the next sequence value,
//!   not NULL.
//! - SQLAlchemy `INSERT INTO t (…) SELECT …` into a narrow (Int32) identity PK —
//!   the synthesized i64 identity values must cast to the column's type.
//! - Django `F()` UPDATE — `SET col = "t"."col" + 1` carries a table qualifier
//!   that must be stripped so it resolves against the update's temp table.
//! - Schema-qualified FK reference (`REFERENCES "public"."u" (id)`) in both
//!   `CREATE TABLE` and `ALTER TABLE … ADD CONSTRAINT` — accepted by taking the
//!   bare table name.

#![allow(clippy::print_stdout)]

use std::sync::Arc;

use arrow_array::{Array, Int32Array, Int64Array};
use basin_catalog::InMemoryCatalog;
use basin_common::ProjectId;
use basin_engine::{Engine, EngineConfig, ExecResult};
use object_store::local::LocalFileSystem;
use tempfile::TempDir;

async fn engine_in(dir: &TempDir) -> Engine {
    let fs = LocalFileSystem::new_with_prefix(dir.path()).unwrap();
    let storage = basin_storage::Storage::new(basin_storage::StorageConfig {
        object_store: Arc::new(fs),
        root_prefix: None,
        disk_cache: basin_integration_tests::cache_defaults::default_test_disk_cache(),
        page_cache: basin_integration_tests::cache_defaults::default_test_page_cache(),
    });
    let catalog: Arc<dyn basin_catalog::Catalog> = Arc::new(InMemoryCatalog::new());
    Engine::new(EngineConfig {
        storage,
        catalog,
        shard: None,
    })
}

fn ids_i64(batches: &[arrow_array::RecordBatch], name: &str) -> Vec<i64> {
    let mut out = Vec::new();
    for b in batches {
        let arr = b
            .column_by_name(name)
            .unwrap_or_else(|| panic!("missing column {name}"))
            .as_any()
            .downcast_ref::<Int64Array>()
            .unwrap_or_else(|| panic!("column {name} is not Int64"));
        for i in 0..arr.len() {
            if !arr.is_null(i) {
                out.push(arr.value(i));
            }
        }
    }
    out
}

fn ids_i32(batches: &[arrow_array::RecordBatch], name: &str) -> Vec<i32> {
    let mut out = Vec::new();
    for b in batches {
        let arr = b
            .column_by_name(name)
            .unwrap_or_else(|| panic!("missing column {name}"))
            .as_any()
            .downcast_ref::<Int32Array>()
            .unwrap_or_else(|| panic!("column {name} is not Int32"));
        for i in 0..arr.len() {
            if !arr.is_null(i) {
                out.push(arr.value(i));
            }
        }
    }
    out
}

/// Drizzle: `INSERT INTO t (id, name) VALUES (default, 'x')`. The explicit
/// `DEFAULT` keyword on a BY DEFAULT identity column must draw nextval, not the
/// NULL that violates the NOT NULL identity column.
#[tokio::test]
async fn explicit_default_keyword_on_identity_draws_nextval() {
    let dir = TempDir::new().unwrap();
    let sess = engine_in(&dir).await.open_session(ProjectId::new()).await.unwrap();

    sess.execute(
        "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL)",
    )
    .await
    .unwrap();
    sess.execute("INSERT INTO t (id, name) VALUES (DEFAULT, 'x'), (DEFAULT, 'y')")
        .await
        .expect("explicit DEFAULT on identity column must succeed");

    let res = sess.execute("SELECT id, name FROM t ORDER BY id").await.unwrap();
    match res {
        ExecResult::Rows { batches, .. } => assert_eq!(ids_i64(&batches, "id"), vec![1, 2]),
        other => panic!("unexpected: {other:?}"),
    }
}

/// SQLAlchemy: `INSERT INTO t (v) SELECT v FROM src` where `t.id` is a narrow
/// INTEGER (Int32) identity PK. The synthesized i64 ids must cast to Int32 so
/// the batch matches the table schema.
#[tokio::test]
async fn insert_select_synthesizes_identity_into_narrow_pk() {
    let dir = TempDir::new().unwrap();
    let sess = engine_in(&dir).await.open_session(ProjectId::new()).await.unwrap();

    sess.execute("CREATE TABLE src (v TEXT NOT NULL)").await.unwrap();
    sess.execute("INSERT INTO src (v) VALUES ('a'), ('b'), ('c')").await.unwrap();
    sess.execute(
        "CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v TEXT NOT NULL)",
    )
    .await
    .unwrap();

    sess.execute("INSERT INTO t (v) SELECT v FROM src")
        .await
        .expect("INSERT-SELECT into narrow identity PK must succeed");

    let res = sess.execute("SELECT id FROM t ORDER BY id").await.unwrap();
    match res {
        ExecResult::Rows { batches, .. } => assert_eq!(ids_i32(&batches, "id"), vec![1, 2, 3]),
        other => panic!("unexpected: {other:?}"),
    }
}

/// Django `F()` expression UPDATE: `SET pages = "books"."pages" + 1`. The table
/// qualifier on the RHS must be stripped so it resolves against the update's
/// temp table rather than failing with "No field named books.pages".
#[tokio::test]
async fn update_set_qualified_self_reference_resolves() {
    let dir = TempDir::new().unwrap();
    let sess = engine_in(&dir).await.open_session(ProjectId::new()).await.unwrap();

    sess.execute("CREATE TABLE books (id BIGINT PRIMARY KEY, pages BIGINT NOT NULL)")
        .await
        .unwrap();
    sess.execute("INSERT INTO books (id, pages) VALUES (1, 100), (2, 200)").await.unwrap();

    sess.execute("UPDATE books SET pages = books.pages + 1")
        .await
        .expect("qualified F()-style UPDATE RHS must resolve");

    let res = sess.execute("SELECT pages FROM books ORDER BY id").await.unwrap();
    match res {
        ExecResult::Rows { batches, .. } => assert_eq!(ids_i64(&batches, "pages"), vec![101, 201]),
        other => panic!("unexpected: {other:?}"),
    }
}

/// Django `bulk_update` emits `SET pages = CASE WHEN "books"."id" = 1 THEN 999
/// ELSE "books"."pages" END` — qualified column refs nested inside a CASE. The
/// SET-RHS qualifier strip must recurse through CASE so it resolves against the
/// update's temp table rather than failing with "No field named books.id".
#[tokio::test]
async fn update_set_case_with_qualified_refs_resolves() {
    let dir = TempDir::new().unwrap();
    let sess = engine_in(&dir).await.open_session(ProjectId::new()).await.unwrap();

    sess.execute("CREATE TABLE books (id BIGINT PRIMARY KEY, pages BIGINT NOT NULL)")
        .await
        .unwrap();
    sess.execute("INSERT INTO books (id, pages) VALUES (1, 10), (2, 20)").await.unwrap();

    // Django wraps the CASE in a cast — `(CASE … END)::integer` — so the strip
    // must recurse through the Cast to reach the inner qualified refs.
    sess.execute(
        "UPDATE books SET pages = (CASE WHEN (books.id = 1) THEN 999 ELSE books.pages END)::bigint",
    )
    .await
    .expect("qualified CASE (cast-wrapped) on the SET RHS must resolve");

    let res = sess.execute("SELECT pages FROM books ORDER BY id").await.unwrap();
    match res {
        ExecResult::Rows { batches, .. } => assert_eq!(ids_i64(&batches, "pages"), vec![999, 20]),
        other => panic!("unexpected: {other:?}"),
    }
}

/// Schema-qualified FK reference in `ALTER TABLE … ADD CONSTRAINT` (Drizzle
/// migrations) — accepted by taking the bare referenced-table name.
#[tokio::test]
async fn alter_add_fk_accepts_schema_qualified_reference() {
    let dir = TempDir::new().unwrap();
    let sess = engine_in(&dir).await.open_session(ProjectId::new()).await.unwrap();

    sess.execute("CREATE TABLE u (id BIGINT NOT NULL PRIMARY KEY)").await.unwrap();
    sess.execute("CREATE TABLE c (id BIGINT NOT NULL PRIMARY KEY, uid BIGINT)").await.unwrap();

    sess.execute(
        "ALTER TABLE c ADD CONSTRAINT c_uid_fk FOREIGN KEY (uid) REFERENCES public.u (id)",
    )
    .await
    .expect("schema-qualified FK reference must be accepted");
}

/// Schema-qualified FK reference in `CREATE TABLE`.
#[tokio::test]
async fn create_table_fk_accepts_schema_qualified_reference() {
    let dir = TempDir::new().unwrap();
    let sess = engine_in(&dir).await.open_session(ProjectId::new()).await.unwrap();

    sess.execute("CREATE TABLE u (id BIGINT NOT NULL PRIMARY KEY)").await.unwrap();
    sess.execute(
        "CREATE TABLE c (id BIGINT NOT NULL PRIMARY KEY, uid BIGINT, \
         CONSTRAINT c_uid_fk FOREIGN KEY (uid) REFERENCES public.u (id))",
    )
    .await
    .expect("schema-qualified FK reference in CREATE TABLE must be accepted");
}
