//! Phase 5.22.B — plain SQL dump (`pg_dump -F p` equivalent).
//!
//! ## Output structure
//!
//! The generated script follows `pg_dump --format=plain` conventions:
//!
//! ```sql
//! -- Basin plain SQL dump
//! -- Format: plain
//! -- Basin version: <CARGO_PKG_VERSION>
//! -- Dump timestamp: <UTC ISO-8601>
//!
//! SET client_encoding = 'UTF8';
//! SET standard_conforming_strings = on;
//!
//! CREATE TABLE "users" ( ... );
//! CREATE TABLE "orders" ( ... );
//!
//! INSERT INTO "users" (...) VALUES (...);
//! ...
//! INSERT INTO "orders" (...) VALUES (...);
//! ```
//!
//! ## Data fidelity
//!
//! - **All standard types**: BIGINT, INTEGER, SMALLINT, TEXT, BOOLEAN,
//!   TIMESTAMPTZ, TIMESTAMP, DATE, NUMERIC(p,s), REAL, DOUBLE PRECISION,
//!   BYTEA (hex-escaped), JSONB, UUID, INET, CIDR, MACADDR, MACADDR8,
//!   TSVECTOR, TSQUERY, CITEXT, MONEY, XML, INT4/INT8/NUM/DATE/TS/TSTZ range
//!   types, BIT(n), BIT VARYING(n), ENUM types, arrays.
//! - **NULL** is emitted as the `NULL` keyword.
//! - **Schema DDL**: PRIMARY KEY, NOT NULL, FOREIGN KEY REFERENCES,
//!   UNIQUE constraints, DEFAULT expressions, GENERATED ALWAYS AS (expr)
//!   STORED, identity columns (GENERATED ALWAYS AS IDENTITY /
//!   GENERATED BY DEFAULT AS IDENTITY).
//! - Tables are emitted in FK dependency order.
//!
//! ## Limitations (v0.1)
//!
//! - Data is emitted as individual `INSERT` statements (not COPY).
//!   A future improvement can switch to `COPY ... FROM stdin` which is
//!   faster for large datasets.
//! - CHECK constraints are not yet re-emitted (Basin stores them in
//!   `TableMetadata::check_constraints` but the round-trip DDL for
//!   generic expressions would need careful quoting).
//! - Sequences backing SERIAL / IDENTITY columns are not separately
//!   re-created; the IDENTITY declaration in the CREATE TABLE is sufficient
//!   for round-tripping within Basin.

use std::fmt::Write;

use arrow_array::{Array, RecordBatch};
use arrow_schema::{DataType, Field, IntervalUnit, TimeUnit};
use basin_catalog::TableMetadata;
use basin_common::{ProjectId, Result};
use chrono::Utc;

use crate::dump::{field_to_pg_type, quote_ident, resolve_tables, DumpOptions};
use crate::types::{
    BASIN_COLUMN_DEFAULT, BASIN_GENERATED_AS, BASIN_IDENTITY, BASIN_IDENTITY_ALWAYS,
    BASIN_TYPE_JSONB, BASIN_TYPE_KEY, BASIN_TYPE_UUID,
};

/// Produce a plain-text SQL dump for `project`.
pub(crate) async fn dump(
    engine: &crate::Engine,
    project: ProjectId,
    opts: &DumpOptions,
) -> Result<String> {
    let catalog = engine.config().catalog.clone();

    // Snapshot the tables at dump-start time.
    let tables = resolve_tables(catalog.as_ref(), &project, opts).await?;

    let mut out = String::with_capacity(4096);
    let ts = Utc::now().format("%Y-%m-%dT%H:%M:%SZ");
    let version = env!("CARGO_PKG_VERSION");

    writeln!(out, "-- Basin plain SQL dump").unwrap();
    writeln!(out, "-- Format: plain").unwrap();
    writeln!(out, "-- Basin version: {version}").unwrap();
    writeln!(out, "-- Dump timestamp: {ts}").unwrap();
    writeln!(out, "-- Note: custom binary format (--format=custom) is NOT").unwrap();
    writeln!(out, "--   byte-compatible with pg_dump custom format.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "SET client_encoding = 'UTF8';").unwrap();
    writeln!(out, "SET standard_conforming_strings = on;").unwrap();
    writeln!(out).unwrap();

    // ── Schema DDL ───────────────────────────────────────────────────────────
    if opts.schema {
        for meta in &tables {
            emit_create_table(&mut out, meta);
        }
    }

    // ── Data ─────────────────────────────────────────────────────────────────
    if opts.data {
        for meta in &tables {
            // Open a session and SELECT * from this table.
            let sess = engine.open_session(project).await?;
            let tname = quote_ident(meta.table.as_str());
            let sql = format!("SELECT * FROM {tname}");
            let result = sess.execute(&sql).await?;

            if let crate::ExecResult::Rows { schema, batches } = result {
                emit_inserts(&mut out, meta.table.as_str(), &schema, &batches);
            }
        }
    }

    Ok(out)
}

/// Restore from a plain SQL dump by replaying each statement through
/// `ProjectSession::execute`.
pub(crate) async fn restore(
    engine: &crate::Engine,
    project: ProjectId,
    sql_script: &str,
) -> Result<()> {
    let sess = engine.open_session(project).await?;

    // Split on statement boundaries. A statement ends at `;` followed by
    // optional whitespace and a newline (or end of string). We use a simple
    // line-accumulation approach: accumulate lines into a buffer; when the
    // accumulated text (trimmed) ends with `;`, it's a complete statement.
    let mut stmt_buf = String::new();

    for line in sql_script.lines() {
        let trimmed = line.trim();

        // Skip empty lines and comments when the buffer is empty.
        if stmt_buf.is_empty() && (trimmed.is_empty() || trimmed.starts_with("--")) {
            continue;
        }

        if !stmt_buf.is_empty() {
            stmt_buf.push('\n');
        }
        stmt_buf.push_str(line);

        // A statement is complete when the trimmed buffer ends with `;`.
        if stmt_buf.trim_end().ends_with(';') {
            let stmt = stmt_buf.trim().to_string();
            stmt_buf.clear();

            // Skip pure comment statements and empty statements.
            let meaningful: &str = stmt.trim_start_matches(|c: char| c == '-' || c.is_whitespace());
            if meaningful.is_empty() || meaningful.starts_with("--") {
                continue;
            }

            sess.execute(&stmt).await?;
        }
    }

    // Execute any unterminated trailing statement.
    let trailing = stmt_buf.trim();
    if !trailing.is_empty() && !trailing.starts_with("--") {
        sess.execute(trailing).await?;
    }

    Ok(())
}

// ─── DDL rendering ───────────────────────────────────────────────────────────

fn emit_create_table(out: &mut String, meta: &TableMetadata) {
    let tname = quote_ident(meta.table.as_str());
    writeln!(out, "CREATE TABLE {tname} (").unwrap();

    let fields = meta.schema.fields();
    let n_fields = fields.len();

    for (i, field) in fields.iter().enumerate() {
        let col_def = render_column_def(field.as_ref(), meta);
        let comma = if i + 1 < n_fields || has_table_constraints(meta) {
            ","
        } else {
            ""
        };
        writeln!(out, "    {col_def}{comma}").unwrap();
    }

    // Table-level PRIMARY KEY constraint.
    if !meta.pk_columns.is_empty() {
        let pk_cols: Vec<String> = meta.pk_columns.iter().map(|c| quote_ident(c)).collect();
        let comma = if !meta.foreign_keys.is_empty() || !meta.unique_constraints.is_empty() {
            ","
        } else {
            ""
        };
        writeln!(out, "    PRIMARY KEY ({}){}", pk_cols.join(", "), comma).unwrap();
    }

    // Table-level FOREIGN KEY constraints.
    let n_fk = meta.foreign_keys.len();
    for (i, fk) in meta.foreign_keys.iter().enumerate() {
        let comma = if i + 1 < n_fk || !meta.unique_constraints.is_empty() {
            ","
        } else {
            ""
        };
        let fk_ddl = render_fk(fk);
        writeln!(out, "    {fk_ddl}{comma}").unwrap();
    }

    // Table-level UNIQUE constraints.
    let n_uq = meta.unique_constraints.len();
    for (i, uq) in meta.unique_constraints.iter().enumerate() {
        let comma = if i + 1 < n_uq { "," } else { "" };
        let cols: Vec<String> = uq.columns.iter().map(|c| quote_ident(c)).collect();
        writeln!(
            out,
            "    CONSTRAINT {} UNIQUE ({}){}",
            quote_ident(&uq.name),
            cols.join(", "),
            comma
        )
        .unwrap();
    }

    writeln!(out, ");").unwrap();
    writeln!(out).unwrap();
}

fn has_table_constraints(meta: &TableMetadata) -> bool {
    !meta.pk_columns.is_empty()
        || !meta.foreign_keys.is_empty()
        || !meta.unique_constraints.is_empty()
}

fn render_column_def(field: &Field, meta: &TableMetadata) -> String {
    let mut col = format!("{} {}", quote_ident(field.name()), field_to_pg_type(field));

    // NOT NULL (skip if the PK constraint already implies it).
    if !field.is_nullable() {
        col.push_str(" NOT NULL");
    }

    // GENERATED ALWAYS AS (expr) STORED.
    if let Some(gen_expr) = field.metadata().get(BASIN_GENERATED_AS) {
        col.push_str(&format!(" GENERATED ALWAYS AS ({gen_expr}) STORED"));
        return col;
    }

    // IDENTITY.
    if let Some(identity_mode) = field.metadata().get(BASIN_IDENTITY) {
        match identity_mode.as_str() {
            BASIN_IDENTITY_ALWAYS => {
                col.push_str(" GENERATED ALWAYS AS IDENTITY");
            }
            _ => {
                col.push_str(" GENERATED BY DEFAULT AS IDENTITY");
            }
        }
        return col;
    }

    // DEFAULT expression (skip the sequence-backed ones that identity handles).
    if let Some(default_expr) = field.metadata().get(BASIN_COLUMN_DEFAULT) {
        // Don't re-emit nextval defaults for SERIAL-expanded columns —
        // the sequence won't exist in the target yet. For other defaults,
        // emit verbatim.
        if !default_expr.starts_with("nextval(") {
            col.push_str(&format!(" DEFAULT {default_expr}"));
        }
    }

    let _ = meta; // may use in future for per-table context
    col
}

fn render_fk(fk: &basin_catalog::ForeignKeyDef) -> String {
    let local_cols: Vec<String> = fk.columns.iter().map(|c| quote_ident(c)).collect();
    let ref_cols: Vec<String> = fk.ref_columns.iter().map(|c| quote_ident(c)).collect();
    let ref_table = quote_ident(&fk.ref_table);

    let on_delete = match fk.on_delete {
        basin_catalog::RefAction::Cascade => " ON DELETE CASCADE",
        basin_catalog::RefAction::NoAction => "",
    };
    let on_update = match fk.on_update {
        basin_catalog::RefAction::Cascade => " ON UPDATE CASCADE",
        basin_catalog::RefAction::NoAction => "",
    };

    format!(
        "CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {}({}){}{}",
        quote_ident(&fk.name),
        local_cols.join(", "),
        ref_table,
        ref_cols.join(", "),
        on_delete,
        on_update,
    )
}

// ─── Data rendering ──────────────────────────────────────────────────────────

fn emit_inserts(
    out: &mut String,
    table_name: &str,
    schema: &arrow_schema::Schema,
    batches: &[RecordBatch],
) {
    let total_rows: usize = batches.iter().map(|b| b.num_rows()).sum();
    if total_rows == 0 {
        return;
    }

    let tname = quote_ident(table_name);
    let col_list: Vec<String> = schema.fields().iter().map(|f| quote_ident(f.name())).collect();
    let cols_str = col_list.join(", ");

    let jsonb_cols: Vec<bool> = schema
        .fields()
        .iter()
        .map(|f| f.metadata().get(BASIN_TYPE_KEY).map(|s| s.as_str()) == Some(BASIN_TYPE_JSONB))
        .collect();
    let uuid_cols: Vec<bool> = schema
        .fields()
        .iter()
        .map(|f| f.metadata().get(BASIN_TYPE_KEY).map(|s| s.as_str()) == Some(BASIN_TYPE_UUID))
        .collect();

    for batch in batches {
        let n_rows = batch.num_rows();
        for r in 0..n_rows {
            let mut row_vals: Vec<String> =
                Vec::with_capacity(schema.fields().len());
            for (c, field) in schema.fields().iter().enumerate() {
                let col = batch.column(c);
                let val = encode_cell(col.as_ref(), r, field.as_ref(), jsonb_cols[c], uuid_cols[c]);
                row_vals.push(val);
            }
            writeln!(
                out,
                "INSERT INTO {tname} ({cols_str}) VALUES ({});",
                row_vals.join(", ")
            )
            .unwrap();
        }
    }
    writeln!(out).unwrap();
}

/// Render one cell value as a SQL literal suitable for embedding in an INSERT.
///
/// Returns `"NULL"` for null cells, otherwise a typed literal.
fn encode_cell(
    col: &dyn Array,
    idx: usize,
    _field: &Field,
    is_jsonb: bool,
    is_uuid: bool,
) -> String {
    use arrow_array::{
        cast::AsArray,
        types::{
            Date32Type, Float32Type, Float64Type, Int16Type, Int32Type, Int64Type, Int8Type,
            IntervalMonthDayNanoType, TimestampMicrosecondType, TimestampMillisecondType,
            TimestampNanosecondType, TimestampSecondType, UInt16Type, UInt32Type, UInt64Type,
            UInt8Type,
        },
    };
    use chrono::{NaiveDate, TimeZone, Utc};

    if col.is_null(idx) {
        return "NULL".to_string();
    }

    match col.data_type() {
        DataType::Boolean => {
            let v = col.as_boolean().value(idx);
            if v { "TRUE".to_string() } else { "FALSE".to_string() }
        }
        DataType::Int8 => format!("{}", col.as_primitive::<Int8Type>().value(idx)),
        DataType::Int16 => format!("{}", col.as_primitive::<Int16Type>().value(idx)),
        DataType::Int32 => format!("{}", col.as_primitive::<Int32Type>().value(idx)),
        DataType::Int64 => format!("{}", col.as_primitive::<Int64Type>().value(idx)),
        DataType::UInt8 => format!("{}", col.as_primitive::<UInt8Type>().value(idx)),
        DataType::UInt16 => format!("{}", col.as_primitive::<UInt16Type>().value(idx)),
        DataType::UInt32 => format!("{}", col.as_primitive::<UInt32Type>().value(idx)),
        DataType::UInt64 => format!("{}", col.as_primitive::<UInt64Type>().value(idx)),
        DataType::Float32 => {
            let v = col.as_primitive::<Float32Type>().value(idx);
            format!("{v}")
        }
        DataType::Float64 => {
            let v = col.as_primitive::<Float64Type>().value(idx);
            format!("{v}")
        }
        DataType::Utf8 => {
            let s = col.as_string::<i32>().value(idx);
            if is_jsonb {
                // JSONB literal: cast so the target knows it's JSON.
                format!("{}::jsonb", crate::dump::sql_quote_str(s))
            } else {
                crate::dump::sql_quote_str(s)
            }
        }
        DataType::LargeUtf8 => {
            let s = col.as_string::<i64>().value(idx);
            if is_jsonb {
                format!("{}::jsonb", crate::dump::sql_quote_str(s))
            } else {
                crate::dump::sql_quote_str(s)
            }
        }
        DataType::Binary => {
            let bytes = col.as_binary::<i32>().value(idx);
            format!("'\\x{}'", hex::encode(bytes))
        }
        DataType::LargeBinary => {
            let bytes = col.as_binary::<i64>().value(idx);
            if is_jsonb {
                // JSONB is stored as canonical JSON bytes (LargeBinary).
                // Emit as a string literal that the engine's JSONB coercer can parse.
                let json_str = std::str::from_utf8(bytes).unwrap_or("{}");
                return format!("'{}'", json_str.replace('\'', "''"));
            }
            if is_uuid {
                // UUID stored as LargeBinary (16 bytes RFC 4122 big-endian).
                if bytes.len() == 16 {
                    let u = uuid::Uuid::from_bytes(bytes.try_into().unwrap_or([0u8; 16]));
                    return format!("'{}'", u.hyphenated());
                }
            }
            format!("'\\x{}'", hex::encode(bytes))
        }
        DataType::FixedSizeBinary(16) if is_uuid => {
            // UUID stored as FixedSizeBinary(16).
            let arr = col
                .as_any()
                .downcast_ref::<arrow_array::FixedSizeBinaryArray>()
                .expect("FixedSizeBinaryArray");
            let bytes: &[u8] = arr.value(idx);
            let u = uuid::Uuid::from_bytes(bytes.try_into().unwrap_or([0u8; 16]));
            format!("'{}'", u.hyphenated())
        }
        DataType::FixedSizeBinary(_) => {
            let arr = col
                .as_any()
                .downcast_ref::<arrow_array::FixedSizeBinaryArray>()
                .expect("FixedSizeBinaryArray");
            let bytes: &[u8] = arr.value(idx);
            format!("'\\x{}'", hex::encode(bytes))
        }
        DataType::Date32 => {
            let days = col.as_primitive::<Date32Type>().value(idx);
            // Days since 1970-01-01
            let epoch = NaiveDate::from_ymd_opt(1970, 1, 1).unwrap();
            let d = epoch + chrono::Duration::days(days as i64);
            format!("'{}'", d.format("%Y-%m-%d"))
        }
        DataType::Timestamp(unit, tz) => {
            let raw: i64 = match unit {
                TimeUnit::Second => col.as_primitive::<TimestampSecondType>().value(idx),
                TimeUnit::Millisecond => {
                    col.as_primitive::<TimestampMillisecondType>().value(idx)
                }
                TimeUnit::Microsecond => {
                    col.as_primitive::<TimestampMicrosecondType>().value(idx)
                }
                TimeUnit::Nanosecond => {
                    col.as_primitive::<TimestampNanosecondType>().value(idx)
                }
            };
            let unix_micros: i64 = match unit {
                TimeUnit::Second => raw.saturating_mul(1_000_000),
                TimeUnit::Millisecond => raw.saturating_mul(1_000),
                TimeUnit::Microsecond => raw,
                TimeUnit::Nanosecond => raw / 1_000,
            };
            let dt = Utc.timestamp_micros(unix_micros).single().unwrap_or_default();
            if tz.is_some() {
                format!("'{}'", dt.format("%Y-%m-%d %H:%M:%S%.6f+00"))
            } else {
                format!("'{}'", dt.naive_utc().format("%Y-%m-%d %H:%M:%S%.6f"))
            }
        }
        DataType::Decimal128(_, scale) => {
            let val = col
                .as_any()
                .downcast_ref::<arrow_array::Decimal128Array>()
                .expect("Decimal128Array")
                .value(idx);
            format_decimal128(val, *scale as u8)
        }
        DataType::Interval(IntervalUnit::MonthDayNano) => {
            let v = col
                .as_primitive::<IntervalMonthDayNanoType>()
                .value(idx);
            let (months, days, nanos) =
                arrow_array::types::IntervalMonthDayNanoType::to_parts(v);
            format!("INTERVAL '{months} months {days} days {nanos} nanoseconds'")
        }
        // List / array types: recurse on element.
        DataType::List(elem_field) => {
            let list_arr = col
                .as_any()
                .downcast_ref::<arrow_array::ListArray>()
                .expect("ListArray");
            let elem_arr = list_arr.value(idx);
            format_array(elem_arr.as_ref(), elem_field.as_ref())
        }
        DataType::LargeList(elem_field) => {
            let list_arr = col
                .as_any()
                .downcast_ref::<arrow_array::LargeListArray>()
                .expect("LargeListArray");
            let elem_arr = list_arr.value(idx);
            format_array(elem_arr.as_ref(), elem_field.as_ref())
        }
        // Fallback: cast to string representation.
        _ => {
            format!("'{}'", format!("{col:?}").replace('\'', "''"))
        }
    }
}

fn format_decimal128(val: i128, scale: u8) -> String {
    if scale == 0 {
        return format!("{val}");
    }
    let divisor = 10i128.pow(scale as u32);
    let int_part = val / divisor;
    let frac_part = (val % divisor).abs();
    format!("{int_part}.{frac_part:0>width$}", width = scale as usize)
}

fn format_array(arr: &dyn Array, elem_field: &Field) -> String {
    let is_jsonb = elem_field
        .metadata()
        .get(BASIN_TYPE_KEY)
        .map(|s| s.as_str())
        == Some(BASIN_TYPE_JSONB);
    let is_uuid = elem_field
        .metadata()
        .get(BASIN_TYPE_KEY)
        .map(|s| s.as_str())
        == Some(BASIN_TYPE_UUID);
    let n = arr.len();
    let mut parts = Vec::with_capacity(n);
    for i in 0..n {
        let v = encode_cell(arr, i, elem_field, is_jsonb, is_uuid);
        parts.push(v);
    }
    format!("ARRAY[{}]", parts.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decimal_format() {
        assert_eq!(format_decimal128(9999, 2), "99.99");
        assert_eq!(format_decimal128(100, 2), "1.00");
        assert_eq!(format_decimal128(0, 2), "0.00");
        assert_eq!(format_decimal128(-100, 2), "-1.00");
    }
}
