#!/usr/bin/env python3
"""
_build_docs_index.py — invoked by build-docs-index.sh.

Usage: python3 scripts/_build_docs_index.py <docs_dir>

Reads every *.md under <docs_dir> (except README.md at the root),
parses YAML frontmatter, and writes a grouped, ordered navigation
index to stdout.
"""
import os
import re
import sys

DOCS_DIR = sys.argv[1]

# Canonical section order from frontmatter-spec.md.
SECTION_ORDER = [
    "overview",
    "architecture",
    "storage",
    "sql",
    "deployment",
    "operations",
    "decisions",
    "reference",
    "meta",
]

SECTION_LABELS = {
    "overview":     "Overview",
    "architecture": "Architecture",
    "storage":      "Storage",
    "sql":          "SQL",
    "deployment":   "Deployment",
    "operations":   "Operations",
    "decisions":    "Architecture decisions (ADRs)",
    "reference":    "Reference",
    "meta":         "Meta",
}


def extract_field(fm_text, field):
    m = re.search(
        r'^' + re.escape(field) + r':\s+"?([^"\n]+)"?\s*$',
        fm_text,
        re.MULTILINE,
    )
    return m.group(1).strip() if m else ""


# Collect docs.
docs = []
for root, dirs, files in os.walk(DOCS_DIR):
    dirs.sort()
    for fname in sorted(files):
        if not fname.endswith(".md"):
            continue
        if fname == "README.md" and root == DOCS_DIR:
            continue
        abs_path = os.path.join(root, fname)
        rel_path = os.path.relpath(abs_path, DOCS_DIR).replace("\\", "/")
        text = open(abs_path, encoding="utf-8").read()
        m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
        if not m:
            print(f"WARNING: no frontmatter in {rel_path}", file=sys.stderr)
            continue
        fm = m.group(1)
        nav_section = extract_field(fm, "nav_section")
        try:
            sidebar_position = int(extract_field(fm, "sidebar_position"))
        except ValueError:
            sidebar_position = 9999
        docs.append({
            "rel_path": rel_path,
            "title": extract_field(fm, "title"),
            "nav_section": nav_section,
            "sidebar_position": sidebar_position,
            "summary": extract_field(fm, "summary"),
        })

# Group and sort.
groups = {s: [] for s in SECTION_ORDER}
for doc in docs:
    sec = doc["nav_section"]
    if sec not in groups:
        groups[sec] = []
        SECTION_ORDER.append(sec)
    groups[sec].append(doc)

for sec in SECTION_ORDER:
    groups[sec].sort(key=lambda d: (d["sidebar_position"], d["rel_path"]))

# Build output lines.
lines = [
    "---",
    'title: "Basin documentation index"',
    "nav_section: overview",
    "sidebar_position: 0",
    'summary: "Top-level navigation for Basin\'s OSS documentation. Both for humans browsing on GitHub and for a downstream docs site fetching this tree at build time."',
    "---",
    "",
    "# Basin documentation",
    "",
    "Navigation root for the Basin OSS repo. Every file is organised by",
    "`nav_section` declared in its YAML frontmatter",
    "(see [`frontmatter-spec.md`](./frontmatter-spec.md)).",
    "A downstream docs site can fetch this index at build time to assemble a",
    "unified nav tree; GitHub renders it for humans browsing `docs/`.",
    "",
]

for sec in SECTION_ORDER:
    sec_docs = groups.get(sec, [])
    if not sec_docs:
        continue
    label = SECTION_LABELS.get(sec, sec.capitalize())
    lines.append(f"## {label}")
    lines.append("")
    for doc in sec_docs:
        path = doc["rel_path"]
        title = doc["title"]
        summary = doc["summary"]
        dash = f" — {summary}" if summary else ""
        lines.append(f"- [{title}]({path}){dash}")
    lines.append("")

lines += [
    "## Project-level documents",
    "",
    "These live at the repo root, not under `docs/`:",
    "",
    "- [`../README.md`](../README.md) — project intro and landing page",
    "- [`../CAPABILITIES.md`](../CAPABILITIES.md) — capability matrix (shipped, in-progress, planned, off-roadmap)",
    "- [`../CHANGELOG.md`](../CHANGELOG.md) — release-by-release shipped changes",
    "- [`../WEDGE.md`](../WEDGE.md) — six-month prioritised roadmap",
    "- [`../TASK.md`](../TASK.md) — full Phase 0–7 build plan, agent-decomposed",
    "- [`../CONTRIBUTING.md`](../CONTRIBUTING.md) — contribution guide",
    "",
    "---",
    "",
    "_This file is generated by [`scripts/build-docs-index.sh`](../scripts/build-docs-index.sh)._",
    "_Re-run the script after adding or editing a doc's frontmatter._",
]

print("\n".join(lines))
