//! Pure PostgreSQL → Basin DDL translation for `basinctl import-from-postgres`.
//!
//! Everything in this module is deterministic and network-free: it takes the
//! introspected source model (`SourceTable` / `SourceColumn` / `EnumType`,
//! filled in by `import::introspect`) and produces per-table [`TablePlan`]s —
//! Basin `CREATE TABLE` SQL, the PG-side `SELECT` projection used by `COPY
//! (SELECT …) TO STDOUT`, the binary-vs-CSV transfer decision, plus a
//! [`Report`] of skipped objects and warnings.
//!
//! ## Type-mapping ground rules
//!
//! - The Basin dialect is whatever `basin_engine::types::arrow_data_type`
//!   accepts (see that match for the canonical list). We never emit a type
//!   name that function rejects.
//! - `serial` / `bigserial` / `smallserial` (detected via a
//!   `nextval('…')` column default) normalise to
//!   `BIGINT GENERATED BY DEFAULT AS IDENTITY` — Basin's identity
//!   convention — with a PG-side `::int8` cast so the binary COPY stream
//!   carries int8, matching the widened target column.
//! - Extension-backed types Basin understands natively (`uuid`, `jsonb`,
//!   `citext`, `vector(N)`) pass straight through.
//! - "Binary-safe" means the *source* type's PG binary COPY wire format is
//!   exactly what Basin's binary COPY decoder expects for the *mapped*
//!   column type (the intersection enforced by
//!   `basin_router::copy::validate_binary_copy_columns`). Everything else
//!   rides the CSV fallback; a single non-binary-safe column flips the
//!   whole table to CSV (COPY is per-table, not per-column).
//! - Unsupported features are *skipped loudly*, never silently: each skip
//!   lands in [`Report::skips`] with a reason and a migration hint
//!   (triggers → Basin reactors, plpgsql → WASM functions, EXCLUDE → manual).

use std::collections::{BTreeMap, HashMap, HashSet};
use std::fmt::Write as _;

// ---------------------------------------------------------------------------
// Source model (filled by import::introspect)
// ---------------------------------------------------------------------------

/// One `CREATE TYPE … AS ENUM` on the source, with labels in sort order.
#[derive(Debug, Clone)]
pub struct EnumType {
    pub schema: String,
    pub name: String,
    pub labels: Vec<String>,
}

/// `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY` flavour.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IdentityKind {
    Always,
    ByDefault,
}

/// One column as seen through `information_schema.columns` joined with
/// `pg_catalog` (for `format_type` and `typtype` — information_schema alone
/// loses vector dims and the enum/composite distinction).
#[derive(Debug, Clone, Default)]
pub struct SourceColumn {
    pub name: String,
    /// `information_schema.columns.data_type` (e.g. `ARRAY`, `USER-DEFINED`).
    pub data_type: String,
    /// `information_schema.columns.udt_name` (e.g. `int4`, `_text`, `vector`).
    pub udt_name: String,
    /// `format_type(atttypid, atttypmod)` — carries modifiers: `vector(384)`,
    /// `numeric(10,2)`, `geometry(Point,4326)`.
    pub formatted_type: String,
    /// `pg_type.typtype`: `b` base, `e` enum, `c` composite, `d` domain,
    /// `r`/`m` range, `p` pseudo.
    pub typtype: String,
    /// For arrays: the element's udt_name (leading `_` stripped) + typtype.
    pub elem_udt: Option<String>,
    pub elem_typtype: Option<String>,
    pub max_len: Option<i32>,
    pub num_precision: Option<i32>,
    pub num_scale: Option<i32>,
    pub not_null: bool,
    pub default: Option<String>,
    pub identity: Option<IdentityKind>,
    /// `GENERATED ALWAYS AS (expr) STORED` expression, if any.
    pub generated_expr: Option<String>,
    /// Set when the column's declared type is a domain (we map the
    /// underlying type and warn).
    pub domain_name: Option<String>,
}

#[derive(Debug, Clone)]
pub struct SourceUnique {
    pub name: String,
    pub columns: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct SourceCheck {
    pub name: String,
    /// `information_schema.check_constraints.check_clause` (bare boolean
    /// expression, no `CHECK` keyword).
    pub clause: String,
}

#[derive(Debug, Clone)]
pub struct SourceFk {
    pub name: String,
    pub columns: Vec<String>,
    pub ref_schema: String,
    pub ref_table: String,
    pub ref_columns: Vec<String>,
    /// `referential_constraints.delete_rule` / `update_rule`
    /// (`NO ACTION` / `CASCADE` / `SET NULL` / `SET DEFAULT` / `RESTRICT`).
    pub on_delete: String,
    pub on_update: String,
}

#[derive(Debug, Clone)]
pub struct SourceTable {
    pub schema: String,
    pub name: String,
    pub columns: Vec<SourceColumn>,
    pub primary_key: Vec<String>,
    pub uniques: Vec<SourceUnique>,
    pub checks: Vec<SourceCheck>,
    pub fks: Vec<SourceFk>,
}

impl SourceTable {
    pub fn qualified(&self) -> String {
        format!("{}.{}", self.schema, self.name)
    }
}

// ---------------------------------------------------------------------------
// Skip / warning report
// ---------------------------------------------------------------------------

/// One object the importer refused to carry over. Printed per-object during
/// the run (loud) and aggregated in the final summary.
#[derive(Debug, Clone)]
pub struct Skip {
    /// `table` / `column` / `constraint` / `trigger` / `function` / `view` /
    /// `materialized view` / `type`.
    pub kind: &'static str,
    /// Schema-qualified object name (`public.users.audit_trg`).
    pub object: String,
    pub reason: String,
    /// What to do instead, when Basin has an answer.
    pub hint: Option<String>,
}

impl Skip {
    pub fn render(&self) -> String {
        let mut s = format!("SKIP {:<10} {} — {}", self.kind, self.object, self.reason);
        if let Some(h) = &self.hint {
            let _ = write!(s, " ({h})");
        }
        s
    }
}

/// Collected skips + soft warnings for the whole import.
#[derive(Debug, Clone, Default)]
pub struct Report {
    pub skips: Vec<Skip>,
    pub warnings: Vec<String>,
}

impl Report {
    pub fn skip(
        &mut self,
        kind: &'static str,
        object: impl Into<String>,
        reason: impl Into<String>,
        hint: Option<&str>,
    ) {
        let s = Skip {
            kind,
            object: object.into(),
            reason: reason.into(),
            hint: hint.map(str::to_owned),
        };
        // Loud, immediate, per-object — the summary repeats it at the end.
        eprintln!("{}", s.render());
        self.skips.push(s);
    }

    pub fn warn(&mut self, msg: impl Into<String>) {
        let m = msg.into();
        eprintln!("WARN {m}");
        self.warnings.push(m);
    }
}

// ---------------------------------------------------------------------------
// Translation output
// ---------------------------------------------------------------------------

/// How a table's rows travel: PG binary COPY end-to-end, or CSV when any
/// column's binary wire format is outside the Basin decoder's set.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Transfer {
    Binary,
    Csv,
}

impl Transfer {
    pub fn as_str(self) -> &'static str {
        match self {
            Transfer::Binary => "binary",
            Transfer::Csv => "csv",
        }
    }
}

/// One column that survives translation and participates in the data copy.
/// (The full type rendering lives in the table's `column_defs`.)
#[derive(Debug, Clone)]
pub struct PlanColumn {
    pub name: String,
    /// PG-side projection expression (already-quoted; may carry casts or
    /// reshaping like range→JSON or point→WKT).
    pub source_expr: String,
    pub binary_safe: bool,
    /// False for `GENERATED … STORED` columns — present in DDL, excluded
    /// from the COPY column list (Basin computes them).
    pub in_copy: bool,
    /// True when the column became a Basin identity column; the importer
    /// bumps `<table>_<col>_seq` via `setval` after the data lands.
    pub identity_seq: bool,
}

/// Everything the importer needs to create + load one table.
#[derive(Debug, Clone)]
pub struct TablePlan {
    pub source_schema: String,
    pub source_name: String,
    /// Bare name on Basin (flat namespace; schema-prefixed on collision).
    pub basin_name: String,
    pub columns: Vec<PlanColumn>,
    pub transfer: Transfer,
    /// Constraint clauses by severity tier so create can retry with
    /// progressively less optional baggage (see [`TablePlan::create_sql`]).
    pk_clause: Option<String>,
    unique_clauses: Vec<String>,
    check_clauses: Vec<(String, String)>, // (constraint name, rendered clause)
    fk_clauses: Vec<(String, String)>,    // (constraint name, rendered clause)
    /// Column definition lines (without constraints).
    column_defs: Vec<String>,
    /// Which import-plan tables this one references (basin names), for
    /// topological scheduling.
    pub fk_parents: Vec<String>,
}

/// Ladder rung for `CREATE TABLE` retries: each step drops one optional
/// constraint tier and records what was dropped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CreateAttempt {
    /// Everything: PK + UNIQUE + CHECK + FK.
    Full,
    /// Drop CHECK constraints (most likely to contain PG-only expressions).
    NoChecks,
    /// Drop CHECKs and FKs (last resort before skipping the table).
    NoChecksNoFks,
}

impl TablePlan {
    /// Render the `CREATE TABLE` for the given retry rung.
    pub fn create_sql(&self, attempt: CreateAttempt) -> String {
        let mut items: Vec<String> = self.column_defs.clone();
        if let Some(pk) = &self.pk_clause {
            items.push(pk.clone());
        }
        items.extend(self.unique_clauses.iter().cloned());
        if attempt == CreateAttempt::Full {
            items.extend(self.check_clauses.iter().map(|(_, c)| c.clone()));
        }
        if attempt != CreateAttempt::NoChecksNoFks {
            items.extend(self.fk_clauses.iter().map(|(_, c)| c.clone()));
        }
        format!(
            "CREATE TABLE {} (\n  {}\n)",
            quote_ident(&self.basin_name),
            items.join(",\n  ")
        )
    }

    pub fn dropped_constraints(&self, attempt: CreateAttempt) -> Vec<String> {
        let mut out = Vec::new();
        if attempt != CreateAttempt::Full {
            out.extend(self.check_clauses.iter().map(|(n, _)| format!("CHECK {n}")));
        }
        if attempt == CreateAttempt::NoChecksNoFks {
            out.extend(
                self.fk_clauses
                    .iter()
                    .map(|(n, _)| format!("FOREIGN KEY {n}")),
            );
        }
        out
    }

    pub fn source_qualified(&self) -> String {
        format!("{}.{}", self.source_schema, self.source_name)
    }

    /// `COPY (SELECT …) TO STDOUT WITH (FORMAT …)` for the source side.
    pub fn copy_out_sql(&self, transfer: Transfer) -> String {
        let exprs: Vec<&str> = self
            .columns
            .iter()
            .filter(|c| c.in_copy)
            .map(|c| c.source_expr.as_str())
            .collect();
        format!(
            "COPY (SELECT {} FROM {}.{}) TO STDOUT WITH (FORMAT {})",
            exprs.join(", "),
            quote_ident(&self.source_schema),
            quote_ident(&self.source_name),
            match transfer {
                Transfer::Binary => "BINARY",
                Transfer::Csv => "CSV",
            }
        )
    }

    /// `COPY t (cols) FROM STDIN WITH (FORMAT …)` for the Basin side.
    pub fn copy_in_sql(&self, transfer: Transfer) -> String {
        let cols: Vec<String> = self
            .columns
            .iter()
            .filter(|c| c.in_copy)
            .map(|c| quote_ident(&c.name))
            .collect();
        format!(
            "COPY {} ({}) FROM STDIN WITH (FORMAT {})",
            quote_ident(&self.basin_name),
            cols.join(", "),
            match transfer {
                Transfer::Binary => "BINARY",
                Transfer::Csv => "CSV",
            }
        )
    }

    /// Identity columns whose backing sequence needs a post-load `setval`.
    pub fn identity_columns(&self) -> Vec<&PlanColumn> {
        self.columns.iter().filter(|c| c.identity_seq).collect()
    }
}

// ---------------------------------------------------------------------------
// Identifier / literal quoting
// ---------------------------------------------------------------------------

/// Double-quote an identifier, doubling internal quotes. Used for both ends
/// (Basin's COPY/DDL paths accept double-quoted identifiers).
pub fn quote_ident(name: &str) -> String {
    format!("\"{}\"", name.replace('"', "\"\""))
}

/// Single-quote a string literal, doubling internal quotes.
pub fn quote_literal(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

/// Result of mapping one source column's type.
enum Mapped {
    Ok {
        basin_type: String,
        binary_safe: bool,
        /// Optional PG-side cast/reshape; `{}` is replaced with the quoted
        /// column reference.
        expr_template: Option<String>,
        warning: Option<String>,
    },
    Unsupported {
        reason: String,
        hint: Option<String>,
    },
}

fn ok(basin_type: impl Into<String>, binary_safe: bool) -> Mapped {
    Mapped::Ok {
        basin_type: basin_type.into(),
        binary_safe,
        expr_template: None,
        warning: None,
    }
}

fn ok_expr(basin_type: impl Into<String>, binary_safe: bool, tpl: &str) -> Mapped {
    Mapped::Ok {
        basin_type: basin_type.into(),
        binary_safe,
        expr_template: Some(tpl.to_owned()),
        warning: None,
    }
}

fn unsupported(reason: impl Into<String>, hint: Option<&str>) -> Mapped {
    Mapped::Unsupported {
        reason: reason.into(),
        hint: hint.map(str::to_owned),
    }
}

/// Extract `(precision, scale)` rendered for NUMERIC, clamping to Basin's
/// Decimal128 ceiling of 38. Bare `numeric` (no typmod) becomes
/// `NUMERIC(38, 18)` — Basin's bare NUMERIC is `(38, 0)`, which would
/// truncate fractional digits.
fn numeric_type(col: &SourceColumn) -> (String, Option<String>, Option<String>) {
    match (col.num_precision, col.num_scale) {
        (Some(p), s) if p >= 1 && p <= 38 => {
            let s = s.unwrap_or(0).clamp(0, p);
            (format!("NUMERIC({p}, {s})"), None, None)
        }
        (Some(p), s) => {
            // Precision beyond Decimal128 — clamp + cast, warn loudly.
            let s = s.unwrap_or(0).clamp(0, 37);
            (
                format!("NUMERIC(38, {s})"),
                Some(format!("{{}}::numeric(38, {s})")),
                Some(format!(
                    "numeric({p}, …) exceeds Basin's NUMERIC(38) ceiling; clamped to NUMERIC(38, {s}) — values needing more than 38 digits will fail the source-side cast"
                )),
            )
        }
        (None, _) => (
            "NUMERIC(38, 18)".to_owned(),
            Some("{}::numeric(38, 18)".to_owned()),
            Some(
                "bare numeric has no fixed precision in Postgres; mapped to NUMERIC(38, 18) — values with more than 20 integer digits will fail the source-side cast"
                    .to_owned(),
            ),
        ),
    }
}

/// Map one base (non-array) udt to Basin. `enums` carries the importable
/// enum types keyed by source type name.
fn map_base_type(
    col: &SourceColumn,
    udt: &str,
    typtype: &str,
    enums: &BTreeMap<String, EnumType>,
) -> Mapped {
    // Enums pass through: the importer emits `CREATE TYPE … AS ENUM` on
    // Basin before any table that uses one. Binary-safe — PG's enum_send
    // is the label text, which Basin decodes as TEXT for the enum-backed
    // Utf8 column.
    if typtype == "e" {
        return if enums.contains_key(udt) {
            ok(quote_ident(udt), true)
        } else {
            unsupported(
                format!("enum type {udt:?} was not found in the source catalog scan"),
                None,
            )
        };
    }
    if typtype == "c" {
        return unsupported(
            "composite types are not supported by Basin",
            Some("flatten the composite into scalar columns or store it as JSONB"),
        );
    }

    match udt {
        "int2" => ok("SMALLINT", true),
        "int4" => ok("INTEGER", true),
        "int8" => ok("BIGINT", true),
        "float4" => ok("REAL", true),
        "float8" => ok("DOUBLE PRECISION", true),
        "bool" => ok("BOOLEAN", true),
        "text" | "name" => ok("TEXT", true),
        "varchar" => match col.max_len {
            Some(n) => ok(format!("VARCHAR({n})"), true),
            None => ok("TEXT", true),
        },
        "bpchar" => match col.max_len {
            Some(n) => ok(format!("CHAR({n})"), true),
            None => ok("TEXT", true),
        },
        "numeric" => {
            let (ty, tpl, warning) = numeric_type(col);
            Mapped::Ok {
                basin_type: ty,
                binary_safe: true,
                expr_template: tpl,
                warning,
            }
        }
        "bytea" => ok("BYTEA", true),
        "date" => ok("DATE", true),
        // TIME's int8-micros binary format is not in Basin's binary COPY
        // codec set (Time64 is missing from validate_binary_copy_columns)
        // — ship it as CSV text.
        "time" => ok("TIME", false),
        "timetz" => unsupported(
            "TIME WITH TIME ZONE is not supported by Basin",
            Some("store as TIME (shift to a fixed zone) or as TEXT"),
        ),
        "timestamp" => ok("TIMESTAMP", true),
        "timestamptz" => ok("TIMESTAMPTZ", true),
        "interval" => Mapped::Ok {
            basin_type: "INTERVAL".to_owned(),
            binary_safe: false,
            expr_template: None,
            warning: Some(
                "interval values travel as Postgres text form; verify a sample after import"
                    .to_owned(),
            ),
        },
        "uuid" => ok("UUID", true),
        "jsonb" => ok("JSONB", true),
        // json: Basin treats JSON as a JSONB synonym (canonicalised). Cast
        // to jsonb on the source so the binary wire format (versioned
        // jsonb_send) matches what Basin's JSONB decoder expects.
        "json" => Mapped::Ok {
            basin_type: "JSONB".to_owned(),
            binary_safe: true,
            expr_template: Some("{}::jsonb".to_owned()),
            warning: Some(
                "json column mapped to JSONB — Basin canonicalises (key order / whitespace not preserved)"
                    .to_owned(),
            ),
        },
        "citext" => ok("CITEXT", true),
        "xml" => ok("XML", true),
        "money" => Mapped::Ok {
            basin_type: "MONEY".to_owned(),
            binary_safe: false,
            // money's binary format is a bare int8 and its text form is
            // locale-decorated ("$1,000.00"); cast through numeric so the
            // CSV cell is a plain decimal Basin's MONEY (Decimal128(20,2))
            // ingest accepts.
            expr_template: Some("{}::numeric".to_owned()),
            warning: None,
        },
        "inet" => ok("INET", false),
        "cidr" => ok("CIDR", false),
        "macaddr" => ok("MACADDR", false),
        "macaddr8" => ok("MACADDR8", false),
        "bit" => match col.max_len {
            Some(n) => ok(format!("BIT({n})"), false),
            None => ok("BIT", false),
        },
        "varbit" => ok("VARBIT", false),
        "tsvector" => ok("TSVECTOR", false),
        "tsquery" => ok("TSQUERY", false),
        // Ranges: Basin stores ranges as a JSON object
        // {"l":…,"u":…,"li":…,"ui":…}. Reshape on the source so the stored
        // form matches what Basin's range operators read. NULL bound =
        // infinite on both sides.
        "int4range" | "int8range" | "numrange" | "daterange" | "tsrange" | "tstzrange" => {
            let tpl = "CASE WHEN {} IS NULL THEN NULL ELSE json_build_object('l', lower({}), 'u', upper({}), 'li', lower_inc({}), 'ui', upper_inc({}))::text END";
            Mapped::Ok {
                basin_type: udt.to_uppercase(),
                binary_safe: false,
                expr_template: Some(tpl.to_owned()),
                warning: Some(
                    "range column reshaped to Basin's JSON range encoding; empty ranges are not representable and will import as their bound pair"
                        .to_owned(),
                ),
            }
        }
        // pgvector — pass through with the dimension recovered from
        // format_type ("vector(384)"); pgvector's text form `[0.1,0.2]`
        // is what Basin's vector ingest parses.
        "vector" => match vector_dim(&col.formatted_type) {
            Some(d) => ok_expr(format!("VECTOR({d})"), false, "{}::text"),
            None => unsupported(
                "vector column has no fixed dimension (bare `vector`)",
                Some("ALTER the source column to vector(N) first — Basin requires a fixed dimension"),
            ),
        },
        // Native PG point → Basin POINT (WKT text form on the wire).
        "point" => ok_expr(
            "POINT",
            false,
            "CASE WHEN {} IS NULL THEN NULL ELSE 'POINT(' || ({})[0]::text || ' ' || ({})[1]::text || ')' END",
        ),
        // PostGIS geometry: only the Point subtype exists in Basin.
        "geometry" => match geometry_subtype(&col.formatted_type) {
            Some((subtype, srid)) if subtype.eq_ignore_ascii_case("point") => {
                let basin = match srid {
                    Some(s) => format!("GEOMETRY(POINT, {s})"),
                    None => "GEOMETRY(POINT)".to_owned(),
                };
                ok_expr(basin, false, "ST_AsText({})")
            }
            Some((subtype, _)) => unsupported(
                format!("PostGIS geometry subtype {subtype:?} is not supported (Basin supports POINT only)"),
                Some("store as WKT TEXT or split into POINT columns"),
            ),
            None => unsupported(
                "untyped PostGIS geometry column (no subtype modifier)",
                Some("Basin supports GEOMETRY(POINT[, srid]) only"),
            ),
        },
        other => unsupported(
            format!("type {other:?} ({}) has no Basin mapping", col.formatted_type),
            None,
        ),
    }
}

/// Pull `N` out of `vector(N)`.
fn vector_dim(formatted: &str) -> Option<u32> {
    let inner = formatted.strip_prefix("vector(")?.strip_suffix(')')?;
    inner.trim().parse().ok()
}

/// Pull `(subtype, srid)` out of `geometry(Point,4326)` / `geometry(Point)`.
fn geometry_subtype(formatted: &str) -> Option<(String, Option<u32>)> {
    let inner = formatted.strip_prefix("geometry(")?.strip_suffix(')')?;
    let mut parts = inner.splitn(2, ',');
    let subtype = parts.next()?.trim().to_owned();
    let srid = parts.next().and_then(|s| s.trim().parse().ok());
    Some((subtype, srid))
}

/// Map a whole column, including array / domain / serial / identity
/// handling. Returns `(basin type rendering, binary_safe, source expr)`.
fn map_column(
    col: &SourceColumn,
    enums: &BTreeMap<String, EnumType>,
    report: &mut Report,
    table_q: &str,
) -> Option<(String, bool, String)> {
    let colref = quote_ident(&col.name);
    let object = format!("{table_q}.{}", col.name);

    if let Some(domain) = &col.domain_name {
        report.warn(format!(
            "{object}: domain {domain:?} flattened to its underlying type ({})",
            col.formatted_type
        ));
    }

    // Arrays: map the element type, require it to be a supported scalar.
    // PG's array text form `{…}` rides CSV (array binary format is not in
    // Basin's codec set).
    if col.data_type == "ARRAY" {
        let elem_udt = col.elem_udt.clone().unwrap_or_default();
        let elem_typtype = col.elem_typtype.clone().unwrap_or_else(|| "b".to_owned());
        let mut elem_col = col.clone();
        // Element typmods (varchar(10)[]) are not split out by
        // information_schema; map the bare element type.
        elem_col.max_len = None;
        match map_base_type(&elem_col, &elem_udt, &elem_typtype, enums) {
            Mapped::Ok { basin_type, .. } => {
                report.warn(format!(
                    "{object}: array values travel as Postgres array literals; verify a sample after import"
                ));
                let mut def = format!("{colref} {basin_type}[]");
                if col.not_null {
                    def.push_str(" NOT NULL");
                }
                return Some((def, false, colref));
            }
            Mapped::Unsupported { reason, hint } => {
                report.skip(
                    "column",
                    object,
                    format!("array of unsupported element type: {reason}"),
                    hint.as_deref(),
                );
                return None;
            }
        }
    }

    // serial / bigserial / smallserial: information_schema shows them as
    // plain ints with a nextval(...) default. Normalise to Basin's identity
    // convention at BIGINT width; cast the outgoing stream to int8 so the
    // binary wire matches the widened column.
    let is_serial = col
        .default
        .as_deref()
        .map(|d| d.trim_start().starts_with("nextval("))
        .unwrap_or(false)
        && matches!(col.udt_name.as_str(), "int2" | "int4" | "int8");
    if is_serial {
        let rendered = format!("{colref} BIGINT GENERATED BY DEFAULT AS IDENTITY");
        return Some((rendered, true, format!("{colref}::int8")));
    }

    let mapped = map_base_type(col, &col.udt_name, &col.typtype, enums);
    let (basin_type, binary_safe, expr_template, warning) = match mapped {
        Mapped::Ok {
            basin_type,
            binary_safe,
            expr_template,
            warning,
        } => (basin_type, binary_safe, expr_template, warning),
        Mapped::Unsupported { reason, hint } => {
            report.skip("column", object, reason, hint.as_deref());
            return None;
        }
    };
    if let Some(w) = warning {
        report.warn(format!("{object}: {w}"));
    }

    let expr = match expr_template {
        Some(tpl) => tpl.replace("{}", &colref),
        None => colref.clone(),
    };

    // Assemble the column definition.
    let mut def = format!("{colref} {basin_type}");
    if let Some(gen) = &col.generated_expr {
        let _ = write!(def, " GENERATED ALWAYS AS ({gen}) STORED");
        report.warn(format!(
            "{object}: generated-column expression copied verbatim; it must be valid Basin SQL (recomputed on Basin, excluded from the data copy)"
        ));
    } else if let Some(kind) = col.identity {
        def.push_str(match kind {
            IdentityKind::Always => " GENERATED ALWAYS AS IDENTITY",
            IdentityKind::ByDefault => " GENERATED BY DEFAULT AS IDENTITY",
        });
        // Identity sequence options (START / INCREMENT) are not supported
        // by Basin and are not carried over; the importer setval()s past
        // MAX(col) after load, which is what matters for inserts.
    } else {
        if col.not_null {
            def.push_str(" NOT NULL");
        }
        if let Some(d) = &col.default {
            if let Some(rendered) = translate_default(d) {
                let _ = write!(def, " DEFAULT {rendered}");
            } else {
                report.warn(format!(
                    "{object}: DEFAULT {d:?} dropped — not in the importer's portable-default set (literals, now()/CURRENT_TIMESTAMP/CURRENT_DATE, gen_random_uuid()/uuid_generate_v4())"
                ));
            }
        }
    }

    Some((def, binary_safe, expr))
}

/// Translate a PG column default into something Basin's DDL accepts, or
/// `None` to drop it (with a warning at the call site). Deliberately a
/// small allowlist: literals, the current-time family, and UUID
/// generation. Everything else is PG-flavoured enough that carrying it
/// over silently would be a lie.
fn translate_default(default: &str) -> Option<String> {
    let d = default.trim();
    // `'lit'::type` — strip the cast, keep the literal.
    let base = match d.find("'::") {
        Some(idx) if d.starts_with('\'') => &d[..=idx],
        _ => d,
    };
    let lower = base.to_ascii_lowercase();
    if lower == "null" || lower.starts_with("null::") {
        return None; // NULL default == no default
    }
    if base.starts_with('\'') && base.ends_with('\'') && base.len() >= 2 {
        return Some(base.to_owned());
    }
    if lower == "true" || lower == "false" {
        return Some(lower);
    }
    if base.parse::<f64>().is_ok() {
        return Some(base.to_owned());
    }
    match lower.as_str() {
        "now()" | "current_timestamp" => Some("now()".to_owned()),
        "current_date" => Some("CURRENT_DATE".to_owned()),
        "gen_random_uuid()" => Some("gen_random_uuid()".to_owned()),
        "uuid_generate_v4()" => Some("uuid_generate_v4()".to_owned()),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Whole-catalog translation
// ---------------------------------------------------------------------------

/// Output of [`translate_catalog`]: ordered table plans, enum DDL to run
/// first, and the level schedule for FK-safe parallel data loading.
#[derive(Debug)]
pub struct Plan {
    pub enum_ddl: Vec<String>,
    pub tables: Vec<TablePlan>,
    /// Indices into `tables`, grouped into FK-dependency levels: every
    /// table's FK parents live in an earlier level, so DDL runs level by
    /// level and data loads parallelise *within* a level without tripping
    /// Basin's FK enforcement on ingest.
    pub levels: Vec<Vec<usize>>,
}

/// Translate the introspected catalog. Skips/warnings accumulate in
/// `report`; tables that cannot be imported at all are dropped from the
/// plan (loudly).
pub fn translate_catalog(tables: &[SourceTable], enums: &[EnumType], report: &mut Report) -> Plan {
    // -- Enum DDL (created before any table references one). Basin's
    // namespace for types is flat per project, like tables.
    let mut enum_map: BTreeMap<String, EnumType> = BTreeMap::new();
    let mut enum_ddl = Vec::new();
    for e in enums {
        if enum_map.contains_key(&e.name) {
            report.warn(format!(
                "enum type {}.{} collides with an enum of the same name in another schema; Basin's type namespace is flat — first one wins",
                e.schema, e.name
            ));
            continue;
        }
        let labels: Vec<String> = e.labels.iter().map(|l| quote_literal(l)).collect();
        enum_ddl.push(format!(
            "CREATE TYPE {} AS ENUM ({})",
            quote_ident(&e.name),
            labels.join(", ")
        ));
        enum_map.insert(e.name.clone(), e.clone());
    }

    // -- Basin names: bare table name, schema-prefixed on collision
    // (Basin's schemas are aliases over one flat namespace).
    let mut name_count: HashMap<&str, usize> = HashMap::new();
    for t in tables {
        *name_count.entry(t.name.as_str()).or_default() += 1;
    }
    let basin_name_of = |t: &SourceTable| -> String {
        if name_count[t.name.as_str()] > 1 && t.schema != "public" {
            format!("{}_{}", t.schema, t.name)
        } else {
            t.name.clone()
        }
    };
    let mut basin_names: HashMap<String, String> = HashMap::new(); // qualified -> basin
    for t in tables {
        let bn = basin_name_of(t);
        if bn != t.name {
            report.warn(format!(
                "{} renamed to {bn:?} on Basin (flat namespace; bare name collides across schemas)",
                t.qualified()
            ));
        }
        basin_names.insert(t.qualified(), bn);
    }

    // -- Per-table translation.
    let mut plans: Vec<TablePlan> = Vec::new();
    'tables: for t in tables {
        let table_q = t.qualified();
        let basin_name = basin_names[&table_q].clone();
        let mut column_defs = Vec::new();
        let mut columns = Vec::new();
        let mut kept: HashSet<&str> = HashSet::new();

        for col in &t.columns {
            match map_column(col, &enum_map, report, &table_q) {
                Some((def, binary_safe, expr)) => {
                    kept.insert(col.name.as_str());
                    let is_serial_identity = def.contains("AS IDENTITY");
                    column_defs.push(def);
                    columns.push(PlanColumn {
                        name: col.name.clone(),
                        source_expr: expr,
                        binary_safe,
                        in_copy: col.generated_expr.is_none(),
                        identity_seq: is_serial_identity,
                    });
                }
                None => {
                    // A NOT NULL column without a default cannot be absent
                    // from Basin's COPY column list — the whole table has
                    // to go.
                    if col.not_null && col.default.is_none() {
                        report.skip(
                            "table",
                            &table_q,
                            format!(
                                "column {:?} is NOT NULL without a default and its type cannot be imported",
                                col.name
                            ),
                            Some("relax the column on the source or migrate this table manually"),
                        );
                        continue 'tables;
                    }
                    if t.primary_key.iter().any(|c| c == &col.name) {
                        report.skip(
                            "table",
                            &table_q,
                            format!("primary-key column {:?} cannot be imported", col.name),
                            None,
                        );
                        continue 'tables;
                    }
                }
            }
        }
        if columns.is_empty() {
            report.skip("table", &table_q, "no importable columns", None);
            continue;
        }

        // PK (all PK columns survived — checked above).
        let pk_clause = if t.primary_key.is_empty() {
            None
        } else {
            let cols: Vec<String> = t.primary_key.iter().map(|c| quote_ident(c)).collect();
            Some(format!("PRIMARY KEY ({})", cols.join(", ")))
        };

        // UNIQUE constraints over surviving columns.
        let mut unique_clauses = Vec::new();
        for u in &t.uniques {
            if u.columns.iter().all(|c| kept.contains(c.as_str())) {
                let cols: Vec<String> = u.columns.iter().map(|c| quote_ident(c)).collect();
                unique_clauses.push(format!(
                    "CONSTRAINT {} UNIQUE ({})",
                    quote_ident(&u.name),
                    cols.join(", ")
                ));
            } else {
                report.skip(
                    "constraint",
                    format!("{table_q}.{}", u.name),
                    "UNIQUE references a column that was not imported",
                    None,
                );
            }
        }

        // CHECK constraints: clause text is copied verbatim — it must be
        // Basin-parseable SQL. The create ladder drops them on failure.
        let check_clauses: Vec<(String, String)> = t
            .checks
            .iter()
            .map(|c| {
                (
                    c.name.clone(),
                    format!("CONSTRAINT {} CHECK ({})", quote_ident(&c.name), c.clause),
                )
            })
            .collect();

        // FKs: rewritten to bare Basin table names. FKs pointing outside
        // the import set, self-referential FKs (unsatisfiable during bulk
        // load — Basin has no ALTER TABLE … ADD FOREIGN KEY to defer
        // them), and FKs over skipped columns are dropped with a report.
        let mut fk_clauses = Vec::new();
        let mut fk_parents = Vec::new();
        for fk in &t.fks {
            let fk_obj = format!("{table_q}.{}", fk.name);
            let ref_q = format!("{}.{}", fk.ref_schema, fk.ref_table);
            let Some(ref_basin) = basin_names.get(&ref_q) else {
                report.skip(
                    "constraint",
                    fk_obj,
                    format!("FOREIGN KEY references {ref_q}, which is not part of this import"),
                    Some("import the referenced table in the same run to keep the constraint"),
                );
                continue;
            };
            if ref_q == table_q {
                report.skip(
                    "constraint",
                    fk_obj,
                    "self-referential FOREIGN KEY cannot be enforced during bulk load (Basin has no ALTER TABLE … ADD FOREIGN KEY)",
                    Some("re-add manually is not yet possible; rows import without the constraint"),
                );
                continue;
            }
            if !fk.columns.iter().all(|c| kept.contains(c.as_str())) {
                report.skip(
                    "constraint",
                    fk_obj,
                    "FOREIGN KEY references a column that was not imported",
                    None,
                );
                continue;
            }
            let cols: Vec<String> = fk.columns.iter().map(|c| quote_ident(c)).collect();
            let ref_cols: Vec<String> = fk.ref_columns.iter().map(|c| quote_ident(c)).collect();
            let mut clause = format!(
                "CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({})",
                quote_ident(&fk.name),
                cols.join(", "),
                quote_ident(ref_basin),
                ref_cols.join(", ")
            );
            if fk.on_delete != "NO ACTION" {
                let _ = write!(clause, " ON DELETE {}", fk.on_delete);
            }
            if fk.on_update != "NO ACTION" {
                let _ = write!(clause, " ON UPDATE {}", fk.on_update);
            }
            fk_clauses.push((fk.name.clone(), clause));
            fk_parents.push(ref_basin.clone());
        }

        let transfer = if columns.iter().filter(|c| c.in_copy).all(|c| c.binary_safe) {
            Transfer::Binary
        } else {
            Transfer::Csv
        };

        plans.push(TablePlan {
            source_schema: t.schema.clone(),
            source_name: t.name.clone(),
            basin_name,
            columns,
            transfer,
            pk_clause,
            unique_clauses,
            check_clauses,
            fk_clauses,
            column_defs,
            fk_parents,
        });
    }

    let levels = topo_levels(&mut plans, report);
    Plan {
        enum_ddl,
        tables: plans,
        levels,
    }
}

/// Group table indices into FK-dependency levels (parents strictly earlier).
/// FK cycles are broken by dropping the in-cycle FKs (loudly) and putting
/// the remainder in one final level.
fn topo_levels(plans: &mut [TablePlan], report: &mut Report) -> Vec<Vec<usize>> {
    let index_of: HashMap<String, usize> = plans
        .iter()
        .enumerate()
        .map(|(i, p)| (p.basin_name.clone(), i))
        .collect();
    let mut level: Vec<Option<usize>> = vec![None; plans.len()];
    let mut levels: Vec<Vec<usize>> = Vec::new();
    loop {
        let mut placed_any = false;
        let mut this_level = Vec::new();
        for i in 0..plans.len() {
            if level[i].is_some() {
                continue;
            }
            let ready = plans[i]
                .fk_parents
                .iter()
                .all(|p| index_of.get(p).map(|&j| level[j].is_some()).unwrap_or(true));
            if ready {
                this_level.push(i);
                placed_any = true;
            }
        }
        if !placed_any {
            break;
        }
        for &i in &this_level {
            level[i] = Some(levels.len());
        }
        levels.push(this_level);
    }
    // Anything unplaced sits on an FK cycle: drop its FKs, warn, final level.
    let remaining: Vec<usize> = (0..plans.len()).filter(|&i| level[i].is_none()).collect();
    if !remaining.is_empty() {
        for &i in &remaining {
            let names: Vec<String> = plans[i].fk_clauses.iter().map(|(n, _)| n.clone()).collect();
            report.skip(
                "constraint",
                format!("{} ({})", plans[i].source_qualified(), names.join(", ")),
                "FOREIGN KEY participates in a reference cycle; dropped to allow bulk load",
                None,
            );
            plans[i].fk_clauses.clear();
            plans[i].fk_parents.clear();
        }
        levels.push(remaining);
    }
    levels
}

// ---------------------------------------------------------------------------
// Tests — pure DDL-translation suite (no network, no server)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, udt: &str) -> SourceColumn {
        SourceColumn {
            name: name.to_owned(),
            udt_name: udt.to_owned(),
            data_type: udt.to_owned(),
            formatted_type: udt.to_owned(),
            typtype: "b".to_owned(),
            ..Default::default()
        }
    }

    fn table(name: &str, columns: Vec<SourceColumn>) -> SourceTable {
        SourceTable {
            schema: "public".to_owned(),
            name: name.to_owned(),
            columns,
            primary_key: vec![],
            uniques: vec![],
            checks: vec![],
            fks: vec![],
        }
    }

    /// Quiet report for tests (still records, just less stderr scraping).
    fn translate_one(t: SourceTable) -> (Plan, Report) {
        let mut report = Report::default();
        let plan = translate_catalog(&[t], &[], &mut report);
        (plan, report)
    }

    #[test]
    fn serial_maps_to_bigint_identity_with_int8_cast() {
        let mut id = col("id", "int4");
        id.not_null = true;
        id.default = Some("nextval('t_id_seq'::regclass)".to_owned());
        let mut t = table("t", vec![id, col("v", "text")]);
        t.primary_key = vec!["id".to_owned()];
        let (plan, _) = translate_one(t);
        let p = &plan.tables[0];
        let ddl = p.create_sql(CreateAttempt::Full);
        assert!(
            ddl.contains("\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY"),
            "ddl: {ddl}"
        );
        assert!(ddl.contains("PRIMARY KEY (\"id\")"), "ddl: {ddl}");
        // Binary stream must carry int8 for the widened column.
        assert_eq!(p.columns[0].source_expr, "\"id\"::int8");
        assert!(p.columns[0].identity_seq);
        assert_eq!(p.transfer, Transfer::Binary);
    }

    #[test]
    fn declared_identity_keeps_width_and_flavour() {
        let mut id = col("id", "int4");
        id.identity = Some(IdentityKind::Always);
        let (plan, _) = translate_one(table("t", vec![id]));
        let ddl = plan.tables[0].create_sql(CreateAttempt::Full);
        assert!(
            ddl.contains("\"id\" INTEGER GENERATED ALWAYS AS IDENTITY"),
            "ddl: {ddl}"
        );
    }

    #[test]
    fn extension_types_pass_through() {
        let mut v = col("emb", "vector");
        v.formatted_type = "vector(384)".to_owned();
        let t = table(
            "t",
            vec![col("u", "uuid"), col("j", "jsonb"), col("c", "citext"), v],
        );
        let (plan, _) = translate_one(t);
        let ddl = plan.tables[0].create_sql(CreateAttempt::Full);
        assert!(ddl.contains("\"u\" UUID"), "ddl: {ddl}");
        assert!(ddl.contains("\"j\" JSONB"), "ddl: {ddl}");
        assert!(ddl.contains("\"c\" CITEXT"), "ddl: {ddl}");
        assert!(ddl.contains("\"emb\" VECTOR(384)"), "ddl: {ddl}");
        // vector has no binary codec on the Basin side → whole table CSV.
        assert_eq!(plan.tables[0].transfer, Transfer::Csv);
    }

    #[test]
    fn binary_safe_table_uses_binary_transfer_and_sql_shapes() {
        let t = table("t", vec![col("a", "int8"), col("b", "text")]);
        let (plan, _) = translate_one(t);
        let p = &plan.tables[0];
        assert_eq!(p.transfer, Transfer::Binary);
        assert_eq!(
            p.copy_out_sql(Transfer::Binary),
            "COPY (SELECT \"a\", \"b\" FROM \"public\".\"t\") TO STDOUT WITH (FORMAT BINARY)"
        );
        assert_eq!(
            p.copy_in_sql(Transfer::Binary),
            "COPY \"t\" (\"a\", \"b\") FROM STDIN WITH (FORMAT BINARY)"
        );
    }

    #[test]
    fn time_and_interval_force_csv() {
        let t = table("t", vec![col("a", "time"), col("b", "interval")]);
        let (plan, _) = translate_one(t);
        assert_eq!(plan.tables[0].transfer, Transfer::Csv);
    }

    #[test]
    fn json_casts_to_jsonb_on_the_wire() {
        let t = table("t", vec![col("doc", "json")]);
        let (plan, _) = translate_one(t);
        let p = &plan.tables[0];
        assert_eq!(p.columns[0].source_expr, "\"doc\"::jsonb");
        assert!(p.create_sql(CreateAttempt::Full).contains("\"doc\" JSONB"));
    }

    #[test]
    fn unsupported_column_is_skipped_with_report() {
        let mut bad = col("snap", "txid_snapshot");
        bad.formatted_type = "txid_snapshot".to_owned();
        let t = table("t", vec![col("id", "int8"), bad]);
        let (plan, report) = translate_one(t);
        let p = &plan.tables[0];
        assert_eq!(p.columns.len(), 1);
        assert!(report
            .skips
            .iter()
            .any(|s| s.kind == "column" && s.object == "public.t.snap"));
    }

    #[test]
    fn not_null_unsupported_column_skips_whole_table() {
        let mut bad = col("snap", "txid_snapshot");
        bad.not_null = true;
        let t = table("t", vec![col("id", "int8"), bad]);
        let (plan, report) = translate_one(t);
        assert!(plan.tables.is_empty());
        assert!(report.skips.iter().any(|s| s.kind == "table"));
    }

    #[test]
    fn timetz_is_skipped() {
        let t = table("t", vec![col("id", "int8"), col("tz", "timetz")]);
        let (plan, report) = translate_one(t);
        assert_eq!(plan.tables[0].columns.len(), 1);
        assert!(report.skips.iter().any(|s| s.object == "public.t.tz"));
    }

    #[test]
    fn enum_columns_pass_through_with_create_type() {
        let mut status = col("status", "order_status");
        status.typtype = "e".to_owned();
        let enums = vec![EnumType {
            schema: "public".to_owned(),
            name: "order_status".to_owned(),
            labels: vec!["new".to_owned(), "shipped".to_owned()],
        }];
        let mut report = Report::default();
        let plan = translate_catalog(&[table("orders", vec![status])], &enums, &mut report);
        assert_eq!(
            plan.enum_ddl,
            vec!["CREATE TYPE \"order_status\" AS ENUM ('new', 'shipped')"]
        );
        assert!(plan.tables[0]
            .create_sql(CreateAttempt::Full)
            .contains("\"status\" \"order_status\""));
        // enum label text is binary-safe.
        assert_eq!(plan.tables[0].transfer, Transfer::Binary);
    }

    #[test]
    fn arrays_map_to_bracket_syntax_and_csv() {
        let mut tags = col("tags", "_text");
        tags.data_type = "ARRAY".to_owned();
        tags.elem_udt = Some("text".to_owned());
        tags.elem_typtype = Some("b".to_owned());
        let (plan, _) = translate_one(table("t", vec![tags]));
        let p = &plan.tables[0];
        assert!(p
            .create_sql(CreateAttempt::Full)
            .contains("\"tags\" TEXT[]"));
        assert_eq!(p.transfer, Transfer::Csv);
    }

    #[test]
    fn numeric_modifiers_and_bare_numeric() {
        let mut exact = col("price", "numeric");
        exact.num_precision = Some(10);
        exact.num_scale = Some(2);
        let bare = col("amount", "numeric");
        let (plan, report) = translate_one(table("t", vec![exact, bare]));
        let ddl = plan.tables[0].create_sql(CreateAttempt::Full);
        assert!(ddl.contains("\"price\" NUMERIC(10, 2)"), "ddl: {ddl}");
        assert!(ddl.contains("\"amount\" NUMERIC(38, 18)"), "ddl: {ddl}");
        assert!(report.warnings.iter().any(|w| w.contains("amount")));
    }

    #[test]
    fn ranges_reshape_to_basin_json_encoding() {
        let t = table("t", vec![col("span", "int4range")]);
        let (plan, _) = translate_one(t);
        let p = &plan.tables[0];
        assert!(p
            .create_sql(CreateAttempt::Full)
            .contains("\"span\" INT4RANGE"));
        assert!(p.columns[0].source_expr.contains("json_build_object"));
        assert_eq!(p.transfer, Transfer::Csv);
    }

    #[test]
    fn point_and_geometry_point_become_wkt() {
        let mut geo = col("loc", "geometry");
        geo.formatted_type = "geometry(Point,4326)".to_owned();
        let t = table("t", vec![col("p", "point"), geo]);
        let (plan, _) = translate_one(t);
        let p = &plan.tables[0];
        let ddl = p.create_sql(CreateAttempt::Full);
        assert!(ddl.contains("\"p\" POINT"), "ddl: {ddl}");
        assert!(ddl.contains("\"loc\" GEOMETRY(POINT, 4326)"), "ddl: {ddl}");
        assert!(p.columns[1].source_expr.contains("ST_AsText"));
    }

    #[test]
    fn geometry_non_point_subtype_is_skipped() {
        let mut geo = col("shape", "geometry");
        geo.formatted_type = "geometry(Polygon,4326)".to_owned();
        let (plan, report) = translate_one(table("t", vec![col("id", "int8"), geo]));
        assert_eq!(plan.tables[0].columns.len(), 1);
        assert!(report.skips.iter().any(|s| s.reason.contains("Polygon")));
    }

    #[test]
    fn fk_orders_levels_and_rewrites_to_basin_names() {
        let mut child_col = col("user_id", "int8");
        child_col.not_null = true;
        let mut child = table("orders", vec![col("id", "int8"), child_col]);
        child.fks = vec![SourceFk {
            name: "orders_user_id_fkey".to_owned(),
            columns: vec!["user_id".to_owned()],
            ref_schema: "public".to_owned(),
            ref_table: "users".to_owned(),
            ref_columns: vec!["id".to_owned()],
            on_delete: "CASCADE".to_owned(),
            on_update: "NO ACTION".to_owned(),
        }];
        let parent = table("users", vec![col("id", "int8")]);
        let mut report = Report::default();
        let plan = translate_catalog(&[child, parent], &[], &mut report);
        // users must land in an earlier level than orders.
        let level_of = |name: &str| {
            plan.levels
                .iter()
                .position(|lvl| lvl.iter().any(|&i| plan.tables[i].basin_name == name))
                .unwrap()
        };
        assert!(level_of("users") < level_of("orders"));
        let orders = plan
            .tables
            .iter()
            .find(|p| p.basin_name == "orders")
            .unwrap();
        let ddl = orders.create_sql(CreateAttempt::Full);
        assert!(
            ddl.contains(
                "CONSTRAINT \"orders_user_id_fkey\" FOREIGN KEY (\"user_id\") REFERENCES \"users\" (\"id\") ON DELETE CASCADE"
            ),
            "ddl: {ddl}"
        );
    }

    #[test]
    fn self_referential_fk_is_dropped() {
        let mut t = table("emp", vec![col("id", "int8"), col("mgr", "int8")]);
        t.fks = vec![SourceFk {
            name: "emp_mgr_fkey".to_owned(),
            columns: vec!["mgr".to_owned()],
            ref_schema: "public".to_owned(),
            ref_table: "emp".to_owned(),
            ref_columns: vec!["id".to_owned()],
            on_delete: "NO ACTION".to_owned(),
            on_update: "NO ACTION".to_owned(),
        }];
        let (plan, report) = translate_one(t);
        assert!(plan.tables[0].fk_clauses.is_empty());
        assert!(report
            .skips
            .iter()
            .any(|s| s.reason.contains("self-referential")));
    }

    #[test]
    fn fk_cycle_is_broken_loudly() {
        let mk_fk = |name: &str, col_: &str, ref_table: &str| SourceFk {
            name: name.to_owned(),
            columns: vec![col_.to_owned()],
            ref_schema: "public".to_owned(),
            ref_table: ref_table.to_owned(),
            ref_columns: vec!["id".to_owned()],
            on_delete: "NO ACTION".to_owned(),
            on_update: "NO ACTION".to_owned(),
        };
        let mut a = table("a", vec![col("id", "int8"), col("b_id", "int8")]);
        a.fks = vec![mk_fk("a_b_fkey", "b_id", "b")];
        let mut b = table("b", vec![col("id", "int8"), col("a_id", "int8")]);
        b.fks = vec![mk_fk("b_a_fkey", "a_id", "a")];
        let mut report = Report::default();
        let plan = translate_catalog(&[a, b], &[], &mut report);
        // Both tables still import (one shared final level), no FKs left.
        assert_eq!(plan.tables.len(), 2);
        assert!(plan.tables.iter().all(|p| p.fk_clauses.is_empty()));
        assert!(report.skips.iter().any(|s| s.reason.contains("cycle")));
    }

    #[test]
    fn fk_to_unimported_table_is_dropped() {
        let mut t = table("orders", vec![col("id", "int8"), col("user_id", "int8")]);
        t.fks = vec![SourceFk {
            name: "orders_user_id_fkey".to_owned(),
            columns: vec!["user_id".to_owned()],
            ref_schema: "other".to_owned(),
            ref_table: "users".to_owned(),
            ref_columns: vec!["id".to_owned()],
            on_delete: "NO ACTION".to_owned(),
            on_update: "NO ACTION".to_owned(),
        }];
        let (plan, report) = translate_one(t);
        assert!(plan.tables[0].fk_clauses.is_empty());
        assert!(report
            .skips
            .iter()
            .any(|s| s.reason.contains("not part of this import")));
    }

    #[test]
    fn cross_schema_name_collision_gets_prefixed() {
        let a = table("users", vec![col("id", "int8")]);
        let mut b = table("users", vec![col("id", "int8")]);
        b.schema = "app".to_owned();
        let mut report = Report::default();
        let plan = translate_catalog(&[a, b], &[], &mut report);
        let names: HashSet<String> = plan.tables.iter().map(|p| p.basin_name.clone()).collect();
        assert!(names.contains("users"));
        assert!(names.contains("app_users"));
    }

    #[test]
    fn create_ladder_drops_checks_then_fks() {
        let mut t = table("t", vec![col("id", "int8"), col("p_id", "int8")]);
        t.checks = vec![SourceCheck {
            name: "t_pos".to_owned(),
            clause: "id > 0".to_owned(),
        }];
        t.fks = vec![SourceFk {
            name: "t_p_fkey".to_owned(),
            columns: vec!["p_id".to_owned()],
            ref_schema: "public".to_owned(),
            ref_table: "p".to_owned(),
            ref_columns: vec!["id".to_owned()],
            on_delete: "NO ACTION".to_owned(),
            on_update: "NO ACTION".to_owned(),
        }];
        let p = table("p", vec![col("id", "int8")]);
        let mut report = Report::default();
        let plan = translate_catalog(&[t, p], &[], &mut report);
        let tp = plan.tables.iter().find(|p| p.basin_name == "t").unwrap();
        let full = tp.create_sql(CreateAttempt::Full);
        assert!(full.contains("CHECK (id > 0)") && full.contains("FOREIGN KEY"));
        let no_checks = tp.create_sql(CreateAttempt::NoChecks);
        assert!(!no_checks.contains("CHECK") && no_checks.contains("FOREIGN KEY"));
        let bare = tp.create_sql(CreateAttempt::NoChecksNoFks);
        assert!(!bare.contains("CHECK") && !bare.contains("FOREIGN KEY"));
        assert_eq!(
            tp.dropped_constraints(CreateAttempt::NoChecksNoFks),
            vec!["CHECK t_pos".to_owned(), "FOREIGN KEY t_p_fkey".to_owned()]
        );
    }

    #[test]
    fn defaults_allowlist() {
        assert_eq!(translate_default("42"), Some("42".to_owned()));
        assert_eq!(translate_default("-1.5"), Some("-1.5".to_owned()));
        assert_eq!(
            translate_default("'pending'::character varying"),
            Some("'pending'".to_owned())
        );
        assert_eq!(translate_default("true"), Some("true".to_owned()));
        assert_eq!(translate_default("now()"), Some("now()".to_owned()));
        assert_eq!(
            translate_default("CURRENT_TIMESTAMP"),
            Some("now()".to_owned())
        );
        assert_eq!(
            translate_default("gen_random_uuid()"),
            Some("gen_random_uuid()".to_owned())
        );
        assert_eq!(translate_default("NULL::text"), None);
        // PG-only expressions are dropped (warned at the call site).
        assert_eq!(translate_default("(random() * 100)"), None);
        assert_eq!(translate_default("my_schema.my_func()"), None);
    }

    #[test]
    fn money_travels_as_plain_numeric_text() {
        let (plan, _) = translate_one(table("t", vec![col("m", "money")]));
        let p = &plan.tables[0];
        assert_eq!(p.columns[0].source_expr, "\"m\"::numeric");
        assert_eq!(p.transfer, Transfer::Csv);
    }

    #[test]
    fn generated_column_kept_in_ddl_but_out_of_copy() {
        let mut g = col("total", "numeric");
        g.num_precision = Some(10);
        g.num_scale = Some(2);
        g.generated_expr = Some("price * qty".to_owned());
        let mut price = col("price", "numeric");
        price.num_precision = Some(10);
        price.num_scale = Some(2);
        let t = table("t", vec![price, col("qty", "int4"), g]);
        let (plan, _) = translate_one(t);
        let p = &plan.tables[0];
        assert!(p
            .create_sql(CreateAttempt::Full)
            .contains("GENERATED ALWAYS AS (price * qty) STORED"));
        assert!(!p.copy_in_sql(p.transfer).contains("\"total\""));
        assert!(!p.copy_out_sql(p.transfer).contains("\"total\""));
    }

    #[test]
    fn quoting_doubles_embedded_quotes() {
        assert_eq!(quote_ident("we\"ird"), "\"we\"\"ird\"");
        assert_eq!(quote_literal("it's"), "'it''s'");
    }
}
